/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["selector", '[data-theme="dark"]'],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bg: "rgb(var(--bg-rgb) / <alpha-value>)",
        surface: "rgb(var(--surface-rgb) / <alpha-value>)",
        "surface-2": "rgb(var(--surface-2-rgb) / <alpha-value>)",
        "surface-raised": "rgb(var(--surface-raised-rgb) / <alpha-value>)",
        "surface-inset": "rgb(var(--surface-inset-rgb) / <alpha-value>)",
        "surface-hover": "rgb(var(--surface-hover-rgb) / <alpha-value>)",
        "surface-selected": "rgb(var(--surface-selected-rgb) / <alpha-value>)",
        sidebar: "rgb(var(--sidebar-rgb) / <alpha-value>)",
        border: "rgb(var(--border-rgb) / <alpha-value>)",
        faint: "rgb(var(--border-faint-rgb) / <alpha-value>)",
        strong: "rgb(var(--border-strong-rgb) / <alpha-value>)",
        text: "rgb(var(--text-rgb) / <alpha-value>)",
        muted: "rgb(var(--muted-rgb) / <alpha-value>)",
        accent: "rgb(var(--accent-rgb) / <alpha-value>)",
        "accent-fill": "rgb(var(--accent-fill-rgb) / <alpha-value>)",
        "accent-fg": "rgb(var(--accent-fg-rgb) / <alpha-value>)",
        "accent-soft": "rgb(var(--accent-soft-rgb) / <alpha-value>)",
        "accent-border": "rgb(var(--accent-border-rgb) / <alpha-value>)",
        link: "rgb(var(--link-rgb) / <alpha-value>)",
        warn: "rgb(var(--warn-rgb) / <alpha-value>)",
        ok: "rgb(var(--ok-rgb) / <alpha-value>)",
        error: "rgb(var(--error-rgb) / <alpha-value>)",
        "series-1": "var(--series-1)",
        "series-2": "var(--series-2)",
        "series-3": "var(--series-3)",
        "series-4": "var(--series-4)",
        "series-5": "var(--series-5)",
        "series-6": "var(--series-6)",
        "series-7": "var(--series-7)",
        "series-8": "var(--series-8)",
        "chart-grid": "var(--chart-grid)",
        "chart-axis": "var(--chart-axis)",
      },
      fontFamily: {
        // The chat/title serif era is over: titles and assistant prose read
        // in the same sans stack now (see docs/ui/deepseek-harness-reference.md).
        // The `serif` key stays so legacy classes resolve instead of dropping.
        serif: ["Inter", "system-ui", "sans-serif"],
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["'JetBrains Mono'", "ui-monospace", "monospace"],
      },
      fontSize: {
        "ui-micro": ["0.625rem", { lineHeight: "0.875rem" }],
        "ui-meta": ["0.6875rem", { lineHeight: "1rem" }],
        "ui-caption": ["0.75rem", { lineHeight: "1rem" }],
        "ui-label": ["0.8125rem", { lineHeight: "1.125rem" }],
        "ui-body": ["0.875rem", { lineHeight: "1.25rem" }],
        "ui-title": ["1.25rem", { lineHeight: "1.75rem" }],
      },
      spacing: {
        compact: "var(--space-compact)",
        panel: "var(--space-panel)",
        card: "var(--space-card)",
        section: "var(--space-section)",
        page: "var(--space-page)",
      },
      height: {
        icon: "var(--density-icon)",
        tool: "var(--density-tool)",
        nav: "var(--density-nav)",
        control: "var(--density-control)",
        primary: "var(--density-primary)",
        header: "var(--density-header)",
        send: "var(--send-button-size)",
        "new-session": "var(--new-session-height)",
      },
      width: {
        icon: "var(--density-icon)",
        tool: "var(--density-tool)",
        nav: "var(--density-nav)",
        control: "var(--density-control)",
        primary: "var(--density-primary)",
        header: "var(--density-header)",
        content: "var(--conversation-content-width)",
        composer: "var(--conversation-composer-width)",
      },
      minHeight: {
        icon: "var(--density-icon)",
        tool: "var(--density-tool)",
        nav: "var(--density-nav)",
        control: "var(--density-control)",
        primary: "var(--density-primary)",
        header: "var(--density-header)",
      },
      borderRadius: {
        small: "var(--radius-small)",
        control: "var(--radius-control)",
        input: "var(--radius-control)",
        card: "var(--radius-card)",
        large: "var(--radius-large)",
        bubble: "var(--radius-bubble)",
        composer: "var(--radius-composer)",
      },
      boxShadow: {
        card: "var(--shadow-card)",
        pop: "var(--shadow-pop)",
        composer: "var(--shadow-card-hover)",
      },
      transitionDuration: {
        fast: "var(--motion-fast)",
        normal: "var(--motion-normal)",
        slow: "var(--motion-slow)",
      },
      transitionTimingFunction: {
        standard: "var(--ease-standard)",
      },
    },
  },
  plugins: [],
};
