/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["selector", '[data-theme="dark"]'],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bg: "var(--bg)",
        surface: "var(--surface)",
        "surface-2": "var(--surface-2)",
        border: "var(--border)",
        faint: "var(--border-faint)",
        text: "var(--text)",
        muted: "var(--muted)",
        accent: "var(--accent)",
        "accent-fg": "var(--accent-fg)",
        link: "var(--link)",
        warn: "var(--warn)",
        ok: "var(--ok)",
        error: "var(--error)",
      },
      fontFamily: {
        serif: ["'Source Serif 4'", "Georgia", "serif"],
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["'JetBrains Mono'", "ui-monospace", "monospace"],
      },
      fontSize: {
        "ui-micro": ["0.625rem", { lineHeight: "0.875rem" }],
        "ui-meta": ["0.6875rem", { lineHeight: "1rem" }],
        "ui-caption": ["0.75rem", { lineHeight: "1rem" }],
        "ui-label": ["0.8125rem", { lineHeight: "1.125rem" }],
        "ui-body": ["0.875rem", { lineHeight: "1.25rem" }],
        "ui-title": ["1.25rem", { lineHeight: "1.75rem" }],
      },
      spacing: {
        compact: "var(--space-compact)",
        panel: "var(--space-panel)",
        card: "var(--space-card)",
        section: "var(--space-section)",
        page: "var(--space-page)",
      },
      height: {
        icon: "var(--density-icon)",
        tool: "var(--density-tool)",
        nav: "var(--density-nav)",
        control: "var(--density-control)",
        primary: "var(--density-primary)",
        header: "var(--density-header)",
      },
      width: {
        icon: "var(--density-icon)",
        tool: "var(--density-tool)",
        nav: "var(--density-nav)",
        control: "var(--density-control)",
        primary: "var(--density-primary)",
        header: "var(--density-header)",
      },
      minHeight: {
        icon: "var(--density-icon)",
        tool: "var(--density-tool)",
        nav: "var(--density-nav)",
        control: "var(--density-control)",
        primary: "var(--density-primary)",
        header: "var(--density-header)",
      },
      borderRadius: {
        card: "14px",
        input: "10px",
      },
      boxShadow: {
        card: "var(--shadow-card)",
        pop: "var(--shadow-pop)",
      },
    },
  },
  plugins: [],
};
