import { createHash, randomUUID } from "node:crypto";
import { createReadStream } from "node:fs";
import { readFile, stat } from "node:fs/promises";
import { basename, extname, join } from "node:path";
import type { FastifyInstance } from "fastify";
import { appendJsonLine, metadataRoot, readJsonLines, workspaceFile } from "./persistence.js";
import { resolveWorkspaceFile, validateWorkspaceCwd } from "./workspace-security.js";

interface Artifact { artifact_id: string; version: number; path: string; kind: string; mime: string; size: number; sha256: string; published_at: string; producer?: Record<string, unknown>; inputs?: unknown[]; environment?: Record<string, unknown>; verification?: Record<string, unknown> }
interface Provenance { path: string; version: number; ts: number; tool: string; toolCallId?: string; sessionId: string; model?: string; contentHash?: string; content?: string; diff?: string; runId?: string }

function q(request: { query: unknown }, key: string, fallback = "."): string { const value = (request.query as Record<string, unknown>)[key]; return typeof value === "string" && value ? value : fallback; }
async function ws(request: { query: unknown }, reply: { code: (status: number) => { send: (body: unknown) => unknown } }): Promise<string | null> { try { return await validateWorkspaceCwd(q(request, "cwd")); } catch (error) { reply.code(403).send({ error: String(error) }); return null; } }
function mime(path: string): string { const table: Record<string, string> = { ".json": "application/json", ".csv": "text/csv", ".txt": "text/plain", ".md": "text/markdown", ".html": "text/html", ".pdf": "application/pdf", ".png": "image/png", ".jpg": "image/jpeg" }; return table[extname(path).toLowerCase()] ?? "application/octet-stream"; }
function kind(path: string, contentType: string): string { if (contentType.startsWith("image/")) return "image"; if (contentType.startsWith("text/") || [".md", ".json", ".yaml", ".yml", ".py", ".sh"].includes(extname(path).toLowerCase())) return "text"; if ([".csv", ".tsv", ".xlsx", ".parquet"].includes(extname(path).toLowerCase())) return "table"; if ([".pdf", ".docx", ".pptx"].includes(extname(path).toLowerCase())) return "document"; return "file"; }

async function recordProvenance(cwd: string, body: Record<string, unknown>): Promise<Provenance> {
  const path = String(body.path ?? "");
  const records = await readJsonLines<Provenance>(workspaceFile(cwd, "provenance.jsonl"));
  const version = records.filter((record) => record.path === path).reduce((max, record) => Math.max(max, record.version), 0) + 1;
  const content = typeof body.content === "string" ? body.content : undefined;
  const record: Provenance = { path, version, ts: Date.now() / 1000, tool: String(body.tool ?? "unknown"), sessionId: String(body.session_id ?? body.sessionId ?? ""), ...(body.tool_call_id ? { toolCallId: String(body.tool_call_id) } : {}), ...(body.model ? { model: String(body.model) } : {}), ...(content !== undefined ? { contentHash: createHash("sha256").update(content).digest("hex").slice(0, 16), content: content.slice(0, 100_000) } : {}), ...(body.diff ? { diff: String(body.diff) } : {}), ...(body.run_id ? { runId: String(body.run_id) } : {}) };
  await appendJsonLine(workspaceFile(cwd, "provenance.jsonl"), record);
  return record;
}

export function registerArtifactRoutes(app: FastifyInstance): void {
  app.get("/api/artifacts", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const query = request.query as { artifact_id?: string; limit?: string }; const all = await readJsonLines<Artifact>(workspaceFile(cwd, "artifacts.jsonl")); const filtered = query.artifact_id ? all.filter((item) => item.artifact_id === query.artifact_id) : all; return { artifacts: filtered.slice(-Math.min(1000, Math.max(1, Number(query.limit ?? 100)))).reverse() }; });
  app.post("/api/artifacts/publish", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const body = (request.body ?? {}) as Record<string, unknown>; const path = String(body.path ?? ""); let target: string; try { target = await resolveWorkspaceFile(cwd, path); } catch (error) { return reply.code(400).send({ error: String(error) }); } let metadata; try { metadata = await stat(target); } catch { return reply.code(404).send({ error: `Artifact not found: ${path}` }); } if (!metadata.isFile()) return reply.code(400).send({ error: "Artifact path is not a file" }); const bytes = await readFile(target); const sha256 = createHash("sha256").update(bytes).digest("hex"); const relative = target.slice(cwd.length + 1).replaceAll("\\", "/"); const artifactId = createHash("sha256").update(`${cwd}:${relative}`).digest("hex").slice(0, 24); const existing = (await readJsonLines<Artifact>(workspaceFile(cwd, "artifacts.jsonl"))).filter((item) => item.artifact_id === artifactId).at(-1); if (existing?.sha256 === sha256) return existing; const artifact: Artifact = { artifact_id: artifactId, version: (existing?.version ?? 0) + 1, path: relative, kind: kind(relative, mime(relative)), mime: mime(relative), size: metadata.size, sha256, published_at: new Date().toISOString(), producer: { tool: body.tool ?? "publish_artifact", session_id: body.session_id ?? "", model: body.model ?? null, run_id: body.run_id ?? null }, inputs: Array.isArray(body.inputs) ? body.inputs : [], environment: typeof body.environment === "object" && body.environment ? body.environment as Record<string, unknown> : {}, verification: { status: "passed", checks: { exists: true, readable: true, size: metadata.size, sha256 }, checked_at: new Date().toISOString() } }; await appendJsonLine(workspaceFile(cwd, "artifacts.jsonl"), artifact); await recordProvenance(cwd, { path: relative, session_id: body.session_id ?? "artifact-publisher", tool: body.tool ?? "publish_artifact", model: body.model, run_id: body.run_id, content: `artifact:${artifactId}:${artifact.version}:${sha256}` }); return artifact; });
  app.get<{ Params: { artifact_id: string } }>("/api/artifacts/:artifact_id", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const query = request.query as { version?: string }; const rows = (await readJsonLines<Artifact>(workspaceFile(cwd, "artifacts.jsonl"))).filter((item) => item.artifact_id === request.params.artifact_id); const item = query.version ? rows.find((row) => row.version === Number(query.version)) : rows.at(-1); return item ?? reply.code(404).send({ error: "Artifact not found" }); });
  app.post("/api/artifacts/verify", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const body = (request.body ?? {}) as Record<string, unknown>; const rows = await readJsonLines<Artifact>(workspaceFile(cwd, "artifacts.jsonl")); const item = rows.filter((row) => row.artifact_id === String(body.artifact_id)).find((row) => body.version ? row.version === Number(body.version) : row.version === Math.max(...rows.filter((row) => row.artifact_id === String(body.artifact_id)).map((row) => row.version))); if (!item) return reply.code(404).send({ error: "Artifact not found" }); try { const target = await resolveWorkspaceFile(cwd, item.path); const bytes = await readFile(target); const actual = createHash("sha256").update(bytes).digest("hex"); const updated = { ...item, verification: { status: actual === item.sha256 ? "passed" : "failed", checks: { sha256: actual, expected: item.sha256 }, checked_at: new Date().toISOString() } }; await appendJsonLine(workspaceFile(cwd, "artifacts.jsonl"), updated); return updated; } catch (error) { return reply.code(404).send({ error: String(error) }); } });
  app.post("/api/artifacts/claim-check", async (request, reply) => { const body = (request.body ?? {}) as Record<string, unknown>; const values = Array.isArray(body.values) ? body.values.map(Number).filter(Number.isFinite) : []; if (!values.length) return reply.code(422).send({ error: "values must contain numbers" }); const direction = body.direction === "positive" || body.direction === "negative" ? body.direction : undefined; const minimum = body.minimum === undefined ? undefined : Number(body.minimum); const maximum = body.maximum === undefined ? undefined : Number(body.maximum); const violations = [...(direction === "positive" && values.some((value) => value < 0) ? ["values must be non-negative"] : []), ...(direction === "negative" && values.some((value) => value > 0) ? ["values must be non-positive"] : []), ...(minimum !== undefined && values.some((value) => value < minimum) ? [`values must be >= ${minimum}`] : []), ...(maximum !== undefined && values.some((value) => value > maximum) ? [`values must be <= ${maximum}`] : [])]; return { claim: String(body.claim ?? ""), status: violations.length ? "failed" : "passed", violations, summary: violations.length ? violations.join("; ") : "claim checks passed" }; });

  app.get("/api/provenance", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const query = request.query as { path?: string; session_id?: string; limit?: string }; let records = await readJsonLines<Provenance>(workspaceFile(cwd, "provenance.jsonl")); if (query.path) records = records.filter((record) => record.path === query.path); if (query.session_id) records = records.filter((record) => record.sessionId === query.session_id); records.reverse(); return { records: records.slice(0, Math.min(1000, Math.max(1, Number(query.limit ?? 100)))), total: records.length }; });
  app.get<{ Params: { path: string } }>("/api/provenance/versions/*", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const path = ((request.params as { path?: string; "*"?: string }).path ?? (request.params as { "*"?: string })["*"] ?? "").replace(/^\//, ""); const records = (await readJsonLines<Provenance>(workspaceFile(cwd, "provenance.jsonl"))).filter((record) => record.path === path); return { path, versions: records }; });
  app.post("/api/provenance/record", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const query = request.query as Record<string, unknown>; const body = (request.body ?? {}) as Record<string, unknown>; return recordProvenance(cwd, { ...query, ...body }); });
  app.post("/api/provenance/capture", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const hash = createHash("sha256").update(`${process.version}:${process.platform}`).digest("hex").slice(0, 16); const text = `${process.version}\nplatform=${process.platform}\narch=${process.arch}\n`; await import("node:fs/promises").then(({ mkdir, writeFile }) => mkdir(join(metadataRoot(cwd), "env"), { recursive: true }).then(() => writeFile(join(metadataRoot(cwd), "env", `${hash}.txt`), text))); return { ts: Date.now() / 1000, label: (request.query as { label?: string }).label ?? null, node: process.version, platform: process.platform, packages_hash: hash, package_count: 0, cpu_count: 1 }; });
  app.get<{ Params: { hash: string } }>("/api/provenance/env/:hash", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; if (!/^[0-9a-f]{16}$/.test(request.params.hash)) return reply.code(400).send({ error: "Invalid environment lockfile hash" }); try { const text = await readFile(join(metadataRoot(cwd), "env", `${request.params.hash}.txt`), "utf8"); return { hash: request.params.hash, text }; } catch { return reply.code(404).send({ error: "Environment lockfile not found" }); } });
}
