import { randomUUID } from "node:crypto";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import type { FastifyInstance } from "fastify";
import { appendJsonLine, metadataRoot, readJson, readJsonLines, workspaceFile, writeJsonAtomic } from "./persistence.js";
import { validateWorkspaceCwd } from "./workspace-security.js";

type Source = { session_id?: string | null; message_ids: string[]; files: string[]; run_ids: string[]; citations: string[] };
type Policy = { auto_review: boolean; reminder_threshold: number; max_directory_depth: number; minimum_files_for_new_category: number; locked_paths: string[]; naming_pattern: string; accepted_counts: Record<string, number>; rejected_counts: Record<string, number>; external_services_allowed: boolean; allowed_egress_domains: string[]; blocked_data_classes: string[]; updated_at: string };
type Item = { id: string; type: string; title: string; summary: string; confidence: string; importance: string; status: string; source: Source; related_files: string[]; conflicts_with: string[]; supersedes: string[]; proposal_id?: string; created_at: string; updated_at: string; [key: string]: unknown };
type Proposal = Item & { proposal_type: "knowledge" | "file_operation"; knowledge_type?: string; reason: string; operations: unknown[]; decision_reason?: string | null; applied_history_id?: string | null };
type ProjectState = { items: Item[]; proposals: Proposal[]; project_versions: Array<{ id: string; created_at: string; reason: string; knowledge_count: number; content: string }>; policy: Policy; history: Array<Record<string, unknown>> };
type RecordRow = { record_id: string; record_type: string; workspace_id: string; loop_id?: string; candidate_id?: string; session_id?: string; run_id?: string; created_at: string; producer: string; payload: Record<string, unknown> };

const defaultPolicy = (): Policy => ({ auto_review: true, reminder_threshold: 5, max_directory_depth: 3, minimum_files_for_new_category: 3, locked_paths: [], naming_pattern: "{date}_{topic}_{kind}_{version}", accepted_counts: {}, rejected_counts: {}, external_services_allowed: true, allowed_egress_domains: [], blocked_data_classes: [], updated_at: new Date().toISOString() });
function q(request: { query: unknown }, key: string, fallback = "."): string { const value = (request.query as Record<string, unknown>)[key]; return typeof value === "string" && value ? value : fallback; }
async function ws(request: { query: unknown }, reply: { code: (status: number) => { send: (body: unknown) => unknown } }): Promise<string | null> { try { return await validateWorkspaceCwd(q(request, "cwd")); } catch (error) { reply.code(403).send({ error: String(error) }); return null; } }
function statePath(cwd: string): string { return workspaceFile(cwd, "project-state.json"); }
async function state(cwd: string): Promise<ProjectState> { const value = await readJson<Partial<ProjectState>>(statePath(cwd), {}); return { items: Array.isArray(value.items) ? value.items : [], proposals: Array.isArray(value.proposals) ? value.proposals : [], project_versions: Array.isArray(value.project_versions) ? value.project_versions : [], policy: { ...defaultPolicy(), ...(value.policy ?? {}) }, history: Array.isArray(value.history) ? value.history : [] }; }
async function projectContent(cwd: string): Promise<string> { const path = join(cwd, "PROJECT.md"); try { return await readFile(path, "utf8"); } catch { return `# ${(cwd.split(/[\\/]/).at(-1) ?? "Project").replaceAll("-", " ")}\n\n## Project Goal / 项目目标\n\nDescribe the project goal, scope, and constraints here.\n`; } }
function source(value: unknown): Source { const input = value && typeof value === "object" ? value as Record<string, unknown> : {}; return { session_id: typeof input.session_id === "string" ? input.session_id : null, message_ids: Array.isArray(input.message_ids) ? input.message_ids.map(String) : [], files: Array.isArray(input.files) ? input.files.map(String) : [], run_ids: Array.isArray(input.run_ids) ? input.run_ids.map(String) : [], citations: Array.isArray(input.citations) ? input.citations.map(String) : [] }; }
function now(): string { return new Date().toISOString(); }
async function records(cwd: string): Promise<RecordRow[]> { return readJsonLines<RecordRow>(workspaceFile(cwd, "research-records.jsonl")); }
async function appendRecord(cwd: string, recordType: string, payload: Record<string, unknown>, extra: Partial<RecordRow> = {}): Promise<RecordRow> { const row: RecordRow = { record_id: `record-${randomUUID().replaceAll("-", "").slice(0, 16)}`, record_type: recordType, workspace_id: cwd, created_at: now(), producer: "node-control-plane", payload, ...extra }; await appendJsonLine(workspaceFile(cwd, "research-records.jsonl"), row); return row; }
function loops(rows: RecordRow[]): Array<Record<string, unknown>> { const result = new Map<string, Record<string, unknown>>(); for (const row of rows) { if (!row.loop_id) continue; if (row.record_type === "loop.created") result.set(row.loop_id, { ...(row.payload), loop_id: row.loop_id }); else if (result.has(row.loop_id) && ["loop.updated", "loop.state_changed"].includes(row.record_type)) result.set(row.loop_id, { ...result.get(row.loop_id), ...row.payload }); } return [...result.values()].sort((a, b) => String(b.updated_at ?? "").localeCompare(String(a.updated_at ?? ""))); }

export function registerProjectRoutes(app: FastifyInstance): void {
  app.get("/api/project-knowledge/summary", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = await state(cwd); return { workspace: cwd, project_file: "PROJECT.md", pending_count: current.proposals.filter((item) => item.status === "pending").length, knowledge_count: current.items.filter((item) => item.status === "active").length, auto_review: current.policy.auto_review }; });
  app.post("/api/project-knowledge/initialize", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = await state(cwd); await writeJsonAtomic(statePath(cwd), current); return { workspace: cwd, project_file: "PROJECT.md", pending_count: 0, knowledge_count: current.items.length, auto_review: current.policy.auto_review }; });
  app.get("/api/project-knowledge/project", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = await state(cwd); return { workspace: cwd, project_file: "PROJECT.md", pending_count: current.proposals.filter((item) => item.status === "pending").length, knowledge_count: current.items.length, auto_review: current.policy.auto_review, content: await projectContent(cwd) }; });
  app.get("/api/project-knowledge/project/versions", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = await state(cwd); return { versions: current.project_versions.slice(-(Number((request.query as { limit?: string }).limit ?? 100))).reverse().map(({ content: _content, ...item }) => item) }; });
  app.post<{ Params: { version_id: string } }>("/api/project-knowledge/project/versions/:version_id/restore", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = await state(cwd); const version = current.project_versions.find((item) => item.id === request.params.version_id); if (!version) return reply.code(404).send({ error: "Project document version not found" }); await mkdir(cwd, { recursive: true }); await writeFile(join(cwd, "PROJECT.md"), version.content, "utf8"); return { ok: true, content: version.content, version_id: version.id }; });
  app.get("/api/project-knowledge/items", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = await state(cwd); const include = String((request.query as { include_inactive?: string }).include_inactive ?? "true") !== "false"; return { items: include ? current.items : current.items.filter((item) => item.status === "active") }; });
  app.get("/api/project-knowledge/proposals", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = await state(cwd); const status = (request.query as { status?: string }).status; const proposals = status ? current.proposals.filter((item) => item.status === status) : current.proposals; return { proposals, pending_count: current.proposals.filter((item) => item.status === "pending").length }; });
  app.get("/api/project-knowledge/proposals/count", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; return { pending_count: (await state(cwd)).proposals.filter((item) => item.status === "pending").length }; });
  app.patch<{ Params: { proposal_id: string } }>("/api/project-knowledge/proposals/:proposal_id", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = await state(cwd); const item = current.proposals.find((row) => row.id === request.params.proposal_id); if (!item) return reply.code(404).send({ error: "Proposal not found" }); if (item.status !== "pending") return reply.code(409).send({ error: "Only pending proposals can be edited" }); Object.assign(item, request.body as Record<string, unknown>, { updated_at: now() }); await writeJsonAtomic(statePath(cwd), current); return { proposal: item }; });
  app.get<{ Params: { proposal_id: string } }>("/api/project-knowledge/proposals/:proposal_id/preview", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const item = (await state(cwd)).proposals.find((row) => row.id === request.params.proposal_id); if (!item) return reply.code(404).send({ error: "Proposal not found" }); return { ok: true, proposal_type: item.proposal_type, before: "", after: `${item.title}\n${item.summary}`, conflicts_with: item.conflicts_with, supersedes: item.supersedes }; });
  app.post<{ Params: { proposal_id: string } }>("/api/project-knowledge/proposals/:proposal_id/accept", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = await state(cwd); const proposal = current.proposals.find((row) => row.id === request.params.proposal_id); if (!proposal) return reply.code(404).send({ error: "Proposal not found" }); if (proposal.status !== "pending") return reply.code(409).send({ error: "Proposal is not pending" }); const body = (request.body ?? {}) as { title?: string; summary?: string }; proposal.status = "accepted"; proposal.updated_at = now(); proposal.decision_reason = null; if (body.title) proposal.title = body.title; if (body.summary) proposal.summary = body.summary; if (proposal.proposal_type === "knowledge") { const item: Item = { id: `knowledge-${randomUUID().replaceAll("-", "").slice(0, 12)}`, type: proposal.knowledge_type ?? "finding", title: proposal.title, summary: proposal.summary, confidence: proposal.confidence, importance: proposal.importance, status: "active", source: proposal.source, related_files: proposal.related_files, conflicts_with: proposal.conflicts_with, supersedes: proposal.supersedes, proposal_id: proposal.id, created_at: now(), updated_at: now() }; current.items.push(item); await writeJsonAtomic(statePath(cwd), current); return { ok: true, proposal_id: proposal.id, knowledge_item: item }; } await writeJsonAtomic(statePath(cwd), current); return { ok: true, proposal_id: proposal.id, file_operation: { id: `history-${randomUUID().slice(0, 12)}`, operations: proposal.operations } }; });
  app.post<{ Params: { proposal_id: string } }>("/api/project-knowledge/proposals/:proposal_id/reject", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = await state(cwd); const proposal = current.proposals.find((row) => row.id === request.params.proposal_id); if (!proposal) return reply.code(404).send({ error: "Proposal not found" }); if (proposal.status !== "pending") return reply.code(409).send({ error: "Proposal is not pending" }); proposal.status = "rejected"; proposal.decision_reason = String(((request.body ?? {}) as { reason?: unknown }).reason ?? ""); proposal.updated_at = now(); await writeJsonAtomic(statePath(cwd), current); return { ok: true, proposal }; });
  app.post("/api/project-knowledge/proposals/batch", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const body = (request.body ?? {}) as { proposal_ids?: unknown; action?: string; reason?: string }; const current = await state(cwd); const failures: unknown[] = []; for (const id of Array.isArray(body.proposal_ids) ? body.proposal_ids.map(String) : []) { const item = current.proposals.find((row) => row.id === id); if (!item || item.status !== "pending") failures.push({ proposal_id: id, status: 409, detail: "Proposal is not pending" }); else { item.status = body.action === "accept" ? "accepted" : "rejected"; item.decision_reason = body.reason ?? null; item.updated_at = now(); } } await writeJsonAtomic(statePath(cwd), current); return { ok: failures.length === 0, results: [], failures }; });
  app.get("/api/project-knowledge/policy", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; return (await state(cwd)).policy; });
  app.patch("/api/project-knowledge/policy", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = await state(cwd); Object.assign(current.policy, request.body as Record<string, unknown>, { updated_at: now() }); await writeJsonAtomic(statePath(cwd), current); return current.policy; });
  app.get("/api/project-knowledge/history", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; return { history: (await state(cwd)).history }; });
  app.get("/api/project-knowledge/files/views", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; return { updated_at: now(), files: [], by_type: {}, by_topic: {}, by_month: {} }; });
  app.post<{ Params: { history_id: string } }>("/api/project-knowledge/file-operations/:history_id/undo", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = await state(cwd); return current.history.some((item) => item.id === request.params.history_id) ? { ok: true, undo: { id: request.params.history_id, status: "not_required" } } : reply.code(404).send({ error: "File operation history not found" }); });

  app.get("/api/project-memory/overview", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = await state(cwd); const rows = await records(cwd); return { workspace: cwd, project_file: "PROJECT.md", pending_count: current.proposals.filter((item) => item.status === "pending").length, knowledge_count: current.items.length, auto_review: current.policy.auto_review, run_count: 0, artifact_count: 0, result_review_count: 0, research_record_count: rows.length, research_loop_count: loops(rows).length, active_research_loop_count: loops(rows).filter((item) => ["ready", "running", "paused", "stopping"].includes(String(item.status))).length }; });
  app.get("/api/project-memory/timeline", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; return { timeline: (await records(cwd)).reverse().slice(0, Number((request.query as { limit?: string }).limit ?? 200)) }; });
  app.post("/api/project-memory/index/rebuild", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; return { ok: true, indexed_at: now(), records: (await records(cwd)).length }; });
  app.get("/api/project-memory/research-loops", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; return { loops: loops(await records(cwd)) }; });
  app.post("/api/project-memory/research-loops", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const body = (request.body ?? {}) as Record<string, unknown>; if (!body.title || !body.objective) return reply.code(400).send({ error: "title and objective are required" }); const loop = { schema_version: 1, loop_id: `loop-${randomUUID().replaceAll("-", "").slice(0, 16)}`, title: String(body.title), objective: String(body.objective), status: "draft", mode: String(body.mode ?? "serial"), evaluator_ref: body.evaluator_ref ?? null, budget: body.budget ?? { max_candidates: 20, max_wall_seconds: 7200, max_parallel: 1 }, stop_conditions: body.stop_conditions ?? { target_metrics: {}, patience: 5, min_improvement: 0 }, constraints: Array.isArray(body.constraints) ? body.constraints : [], created_by: "user", created_at: now(), updated_at: now(), stop_reason: null }; await appendRecord(cwd, "loop.created", loop, { loop_id: loop.loop_id }); return loop; });
  app.get<{ Params: { loop_id: string } }>("/api/project-memory/research-loops/:loop_id", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const row = loops(await records(cwd)).find((item) => item.loop_id === request.params.loop_id); return row ? { ...row, experiences: [], frontier: [] } : reply.code(404).send({ error: "Research loop not found" }); });
  app.patch<{ Params: { loop_id: string } }>("/api/project-memory/research-loops/:loop_id", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = loops(await records(cwd)).find((item) => item.loop_id === request.params.loop_id); if (!current) return reply.code(404).send({ error: "Research loop not found" }); if (!["draft", "paused"].includes(String(current.status))) return reply.code(409).send({ error: "Only draft or paused loops can be edited" }); const changes = request.body as Record<string, unknown>; await appendRecord(cwd, "loop.updated", { ...changes, updated_at: now() }, { loop_id: request.params.loop_id }); return { ...current, ...changes, updated_at: now() }; });
  app.post<{ Params: { loop_id: string; action: string } }>("/api/project-memory/research-loops/:loop_id/:action", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = loops(await records(cwd)).find((item) => item.loop_id === request.params.loop_id); const target: Record<string, string> = { start: "running", pause: "paused", resume: "running", cancel: "cancelled", complete: "completed" }; if (!current) return reply.code(404).send({ error: "Research loop not found" }); const next = target[request.params.action]; if (!next) return reply.code(404).send({ error: "Unknown research loop action" }); const allowed: Record<string, string[]> = { draft: ["ready", "cancelled"], ready: ["running", "cancelled"], running: ["paused", "completed", "cancelled"], paused: ["running", "cancelled"] }; if (!allowed[String(current.status)]?.includes(next)) return reply.code(409).send({ error: `Invalid loop transition: ${current.status} -> ${next}` }); const payload = { status: next, updated_at: now(), ...(next === "completed" || next === "cancelled" ? { stop_reason: `user_${request.params.action}` } : {}) }; await appendRecord(cwd, "loop.state_changed", payload, { loop_id: request.params.loop_id }); return { ...current, ...payload }; });
  app.get("/api/project-memory/evaluators", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; return { evaluators: (await records(cwd)).filter((row) => row.record_type === "evaluator.registered").map((row) => row.payload) }; });
  app.post("/api/project-memory/evaluators", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const body = (request.body ?? {}) as Record<string, unknown>; if (!body.evaluator_id || !body.digest) return reply.code(400).send({ error: "evaluator_id and digest are required" }); const existing = (await records(cwd)).find((row) => row.record_type === "evaluator.registered" && row.payload.evaluator_id === body.evaluator_id && row.payload.version === body.version); if (existing) return reply.code(409).send({ error: "Evaluator version already exists" }); const row = await appendRecord(cwd, "evaluator.registered", body); return { record_id: row.record_id, evaluator: body }; });
  app.get<{ Params: { evaluator_id: string; version: string } }>("/api/project-memory/evaluators/:evaluator_id/versions/:version", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const row = (await records(cwd)).find((item) => item.record_type === "evaluator.registered" && item.payload.evaluator_id === request.params.evaluator_id && Number(item.payload.version) === Number(request.params.version)); return row?.payload ?? reply.code(404).send({ error: "Evaluator version not found" }); });
}
