import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import type { FastifyInstance } from "fastify";
import { configPath, readJson, readJsonLines, workspaceFile, writeJsonAtomic, appendJsonLine } from "./persistence.js";
import { endpointId } from "./settings-routes.js";
import { validateWorkspaceCwd } from "./workspace-security.js";

function cwd(request: { query: unknown }): string { const value = (request.query as Record<string, unknown>).cwd; return typeof value === "string" && value ? value : "."; }
async function ws(request: { query: unknown }, reply: { code: (status: number) => { send: (body: unknown) => unknown } }): Promise<string | null> { try { return await validateWorkspaceCwd(cwd(request)); } catch (error) { reply.code(403).send({ error: String(error) }); return null; } }
type Endpoint = { endpoint_id: string; name: string; base_url: string; protocol: string; enabled: boolean; health: string; model_schema: Record<string, unknown>; rate_limit: Record<string, unknown>; secret_ref?: string | null; data_egress: string; error?: string | null };

export function registerRunEndpointRoutes(app: FastifyInstance): void {
  app.get("/api/runs", async (request, reply) => { const root = await ws(request, reply); if (!root) return; return (await readJsonLines<Record<string, unknown>>(workspaceFile(root, "runs.jsonl"))).reverse().slice(0, 100); });
  app.post("/api/runs", async (request, reply) => { const root = await ws(request, reply); if (!root) return; const query = request.query as Record<string, unknown>; const body = (request.body ?? {}) as Record<string, unknown>; const record = { runId: String(body.run_id ?? query.run_id ?? `run_${Date.now()}`), command: String(body.command ?? query.command ?? ""), surface: String(body.surface ?? query.surface ?? "local"), host: String(body.host ?? query.host ?? ""), status: String(body.status ?? query.status ?? "ok"), startedAt: new Date().toISOString(), outputs: Array.isArray(body.outputs) ? body.outputs : [], ...(body.log ? { log: String(body.log) } : {}) }; await appendJsonLine(workspaceFile(root, "runs.jsonl"), record); return record; });
  app.get<{ Params: { run_id: string } }>("/api/runs/:run_id/log", async (request, reply) => { const root = await ws(request, reply); if (!root) return; const record = (await readJsonLines<Record<string, unknown>>(workspaceFile(root, "runs.jsonl"))).find((item) => item.runId === request.params.run_id); return record ? { log: String(record.log ?? ""), run: record } : { log: "", error: "Run not found" }; });

  app.get("/api/endpoints", async () => ({ endpoints: await readJson<Endpoint[]>(configPath("model-endpoints.json"), []) }));
  app.post("/api/endpoints", async (request, reply) => { const body = (request.body ?? {}) as Record<string, unknown>; const name = String(body.name ?? "").trim(); const baseUrl = String(body.base_url ?? "").trim().replace(/\/$/, ""); if (!name || !/^https?:\/\//.test(baseUrl)) return reply.code(400).send({ error: "model endpoint name and absolute http(s) base_url are required" }); const endpoint: Endpoint = { endpoint_id: endpointId(name, baseUrl), name, base_url: baseUrl, protocol: String(body.protocol ?? "unknown"), enabled: true, health: "unknown", model_schema: typeof body.model_schema === "object" && body.model_schema ? body.model_schema as Record<string, unknown> : {}, rate_limit: typeof body.rate_limit === "object" && body.rate_limit ? body.rate_limit as Record<string, unknown> : {}, secret_ref: body.secret_ref ? String(body.secret_ref) : null, data_egress: String(body.data_egress ?? "remote"), error: null }; const rows = await readJson<Endpoint[]>(configPath("model-endpoints.json"), []); await writeJsonAtomic(configPath("model-endpoints.json"), [...rows.filter((row) => row.endpoint_id !== endpoint.endpoint_id), endpoint]); return endpoint; });
  app.put<{ Params: { endpoint_id: string } }>("/api/endpoints/:endpoint_id/enabled", async (request, reply) => { const rows = await readJson<Endpoint[]>(configPath("model-endpoints.json"), []); const item = rows.find((row) => row.endpoint_id === request.params.endpoint_id); if (!item) return reply.code(404).send({ error: "Model endpoint not found" }); const enabled = String((request.query as { enabled?: string }).enabled ?? "true") !== "false"; item.enabled = enabled; if (!enabled) item.health = "blocked"; await writeJsonAtomic(configPath("model-endpoints.json"), rows); return item; });
  app.post<{ Params: { endpoint_id: string } }>("/api/endpoints/:endpoint_id/health", async (request, reply) => { const rows = await readJson<Endpoint[]>(configPath("model-endpoints.json"), []); const item = rows.find((row) => row.endpoint_id === request.params.endpoint_id); if (!item) return reply.code(404).send({ error: "Model endpoint not found" }); if (!item.enabled) { item.health = "blocked"; item.error = "endpoint disabled"; } else { try { const response = await fetch(item.base_url, { signal: AbortSignal.timeout(8_000) }); item.health = response.ok ? "ready" : "degraded"; item.error = null; } catch (error) { item.health = "error"; item.error = String(error).slice(0, 300); } } await writeJsonAtomic(configPath("model-endpoints.json"), rows); return item; });
}
