import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import type { FastifyInstance, FastifyReply } from "fastify";
import { configPath, readJson, writeJsonAtomic } from "./persistence.js";
import { nodeSessionService } from "./node-session-service.js";
import { runtimeExtensionStatus } from "./pi-runtime-launch.js";

const PROVIDER_ENV: Record<string, string> = { anthropic: "ANTHROPIC_API_KEY", openai: "OPENAI_API_KEY", google: "GEMINI_API_KEY", deepseek: "DEEPSEEK_API_KEY", groq: "GROQ_API_KEY", openrouter: "OPENROUTER_API_KEY", mistral: "MISTRAL_API_KEY", xai: "XAI_API_KEY", zai: "ZAI_API_KEY", fireworks: "FIREWORKS_API_KEY", together: "TOGETHER_API_KEY" };
const PROVIDERS = [
  ["anthropic", "Anthropic", ["claude-opus-4-5", "claude-sonnet-4-20250514"]], ["openai", "OpenAI", ["gpt-5.1", "gpt-5.1-codex", "gpt-4o"]], ["google", "Gemini", ["gemini-2.5-pro", "gemini-2.5-flash"]], ["deepseek", "DeepSeek", ["deepseek-v4-pro", "deepseek-v4-flash"]], ["groq", "Groq", ["llama-3.3-70b-versatile"]], ["openrouter", "OpenRouter", ["openai/gpt-5.1", "anthropic/claude-sonnet-5"]], ["mistral", "Mistral", ["devstral-latest"]], ["xai", "xAI", ["grok-4.3"]], ["zai", "Z.AI", ["glm-4.7"]],
] as const;
type Settings = { api_keys?: Record<string, string>; model?: string; thinking?: string; custom_providers?: Array<{ id: string; name: string; base_url: string; api_key?: string; api: string; models: string[] }>; web_access?: Record<string, unknown>; mcp_servers?: string[]; skills_configured?: boolean; skill_paths?: string[]; model_endpoints?: unknown[]; [key: string]: unknown };

let settingsWrites: Promise<void> = Promise.resolve();
async function load(): Promise<Settings> { await settingsWrites.catch(() => undefined); return readJson<Settings>(configPath("config.json"), {}); }
async function mutate<T>(operation: (config: Settings) => T | Promise<T>): Promise<T> {
  const pending = settingsWrites.catch(() => undefined).then(async () => {
    const config = await readJson<Settings>(configPath("config.json"), {});
    const result = await operation(config);
    await writeJsonAtomic(configPath("config.json"), config);
    return result;
  });
  settingsWrites = pending.then(() => undefined, () => undefined);
  return pending;
}
async function reloadRuntimes(): Promise<Array<{ cwd: string; oldId: string; newId: string }>> { return nodeSessionService.reloadConfiguration(); }
async function respondWithReload<T extends Record<string, unknown>>(reply: FastifyReply, payload: T): Promise<(T & { session_replacements: Array<{ cwd: string; oldId: string; newId: string }> }) | FastifyReply> {
  try { return { ...payload, session_replacements: await reloadRuntimes() }; }
  catch (error) { return reply.code(502).send({ ok: false, error: `Settings were saved, but Pi runtime reload failed: ${String(error)}` }); }
}
function active(config: Settings): Record<string, boolean> { return Object.fromEntries(Object.keys(PROVIDER_ENV).map((id) => [id, Boolean(config.api_keys?.[id] || process.env[PROVIDER_ENV[id]!] || (id === "openai" && process.env.OPENAI_API_KEY))])); }
function models(config: Settings): Array<Record<string, unknown>> { const result: Array<Record<string, unknown>> = []; for (const [id, name, entries] of PROVIDERS) if (active(config)[id]) for (const model of entries) result.push({ id: `${id}/${model}`, provider: id, model, label: `${name} · ${model}`, custom: false, reasoning: /gpt-5|thinking|reasoning|claude-(opus|sonnet)-4|gemini-2.5/.test(model), thinking_levels: ["off", "low", "medium", "high"] }); for (const provider of config.custom_providers ?? []) for (const model of provider.models) result.push({ id: `custom-${provider.id}/${model}`, provider: `custom-${provider.id}`, model, label: `${provider.name} · ${model}`, custom: true, reasoning: /thinking|reasoning|gpt-5|qwen3|deepseek-r1/i.test(model), thinking_levels: ["off", "low", "medium", "high"] }); return result; }
function publicCustom(item: NonNullable<Settings["custom_providers"]>[number]): Record<string, unknown> { return { id: item.id, name: item.name, base_url: item.base_url, api: item.api, models: item.models, has_key: Boolean(item.api_key) }; }
function slug(value: string): string { return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 48) || "custom-api"; }
function query(request: { query: unknown }, name: string, fallback = "."): string { const value = (request.query as Record<string, unknown>)[name]; return typeof value === "string" && value ? value : fallback; }

export function registerSettingsRoutes(app: FastifyInstance): void {
  app.get("/api/settings/providers", async () => { const config = await load(); return { providers: PROVIDERS.map(([id, name, modelList]) => ({ id, name, models: modelList, has_key: active(config)[id] })) }; });
  app.get("/api/settings/config", async () => { const config = await load(); const available = models(config); const configured = typeof config.model === "string" && available.some((item) => item.id === config.model) ? config.model : ""; return { api_keys: active(config), model: configured, thinking: configured ? String(config.thinking ?? "high") : "off", providers: PROVIDERS.map(([id, name, modelList]) => ({ id, name, models: modelList, has_key: active(config)[id] })), custom_providers: (config.custom_providers ?? []).map(publicCustom), available_models: available }; });
  app.put("/api/settings/api-key", async (request, reply) => { const body = (request.body ?? {}) as { provider?: unknown; api_key?: unknown }; const provider = String(body.provider ?? ""); if (!PROVIDER_ENV[provider]) return reply.code(400).send({ error: `Unknown provider: ${provider}` }); await mutate((config) => { config.api_keys = { ...(config.api_keys ?? {}), [provider]: String(body.api_key ?? "") }; }); return respondWithReload(reply, { ok: true, provider }); });
  app.delete<{ Params: { provider: string } }>("/api/settings/api-key/:provider", async (request, reply) => { await mutate((config) => { if (config.api_keys) delete config.api_keys[request.params.provider]; if (String(config.model ?? "").startsWith(`${request.params.provider}/`)) config.model = ""; }); return respondWithReload(reply, { ok: true, provider: request.params.provider }); });
  app.put("/api/settings/model", async (request, reply) => { const body = (request.body ?? {}) as { model?: unknown; thinking?: unknown }; const model = String(body.model ?? ""); const thinking = String(body.thinking ?? "high"); const accepted = await mutate((config) => { if (model && !models(config).some((item) => item.id === model)) return false; config.model = model; config.thinking = thinking; return true; }); if (!accepted) return reply.code(400).send({ error: "Model requires a configured provider" }); return respondWithReload(reply, { ok: true, model, thinking }); });
  app.get("/api/settings/custom-providers", async () => ({ providers: (await load()).custom_providers?.map(publicCustom) ?? [] }));
  app.post("/api/settings/custom-providers/discover", async (request, reply) => { const body = (request.body ?? {}) as Record<string, unknown>; const baseUrl = String(body.base_url ?? "").replace(/\/$/, ""); if (!/^https?:\/\//.test(baseUrl)) return reply.code(400).send({ error: "base_url must be an absolute http(s) URL" }); const headers: Record<string, string> = { accept: "application/json" }; if (body.api_key) headers.authorization = `Bearer ${String(body.api_key)}`; let response: Response; try { response = await fetch(`${baseUrl}/models`, { headers, signal: AbortSignal.timeout(10_000) }); } catch (error) { return reply.code(502).send({ error: `Model discovery failed: ${String(error)}` }); } const payload = await response.json().catch(() => ({})) as Record<string, unknown>; if (!response.ok) return reply.code(502).send({ error: String(payload.error ?? payload.message ?? `Model discovery returned ${response.status}`) }); const rows = Array.isArray(payload.data) ? payload.data : Array.isArray(payload.models) ? payload.models : []; const discovered = rows.map((item) => typeof item === "string" ? item : item && typeof item === "object" ? String((item as Record<string, unknown>).id ?? (item as Record<string, unknown>).name ?? "") : "").filter(Boolean); if (!discovered.length) return reply.code(422).send({ error: "No models were returned by this provider" }); const id = slug(String(body.name ?? new URL(baseUrl).hostname)); return { provider: { id, name: String(body.name ?? "Custom API"), base_url: baseUrl, api: String(body.api ?? "openai-completions"), models: [...new Set(discovered)] } }; });
  app.put<{ Params: { provider_id: string } }>("/api/settings/custom-providers/:provider_id", async (request, reply) => { const body = (request.body ?? {}) as Record<string, unknown>; const baseUrl = String(body.base_url ?? "").replace(/\/$/, ""); if (!/^https?:\/\//.test(baseUrl)) return reply.code(400).send({ error: "base_url must be an absolute http(s) URL" }); const modelList = Array.isArray(body.models) ? [...new Set(body.models.map(String).map((item) => item.trim()).filter(Boolean))] : []; if (!modelList.length) return reply.code(400).send({ error: "At least one model is required" }); const requestedId = request.params.provider_id; const id = slug(requestedId); const result = await mutate((config) => { const old = config.custom_providers?.find((item) => item.id === id); if (old && requestedId !== old.id) return { conflict: true as const }; const requestedKey = String(body.api_key ?? ""); const next = { id, name: String(body.name ?? "Custom API"), base_url: baseUrl, api: String(body.api ?? "openai-completions"), models: modelList, api_key: requestedKey || old?.api_key || "" }; config.custom_providers = [...(config.custom_providers ?? []).filter((item) => item.id !== id), next]; return { conflict: false as const, provider: next }; }); if (result.conflict) return reply.code(409).send({ error: `Provider ID '${requestedId}' conflicts with existing provider '${id}'` }); return respondWithReload(reply, { ok: true, provider: publicCustom(result.provider) }); });
  app.delete<{ Params: { provider_id: string } }>("/api/settings/custom-providers/:provider_id", async (request, reply) => { const id = slug(request.params.provider_id); await mutate((config) => { config.custom_providers = (config.custom_providers ?? []).filter((item) => item.id !== id); if (String(config.model ?? "").startsWith(`custom-${id}/`)) config.model = ""; }); return respondWithReload(reply, { ok: true, id }); });
  app.get("/api/settings/web-access", async () => { const config = await load(); const web = config.web_access ?? {}; const stored = typeof web.api_keys === "object" && web.api_keys ? web.api_keys as Record<string, string> : {}; return { provider: typeof web.provider === "string" ? web.provider : "auto", workflow: typeof web.workflow === "string" ? web.workflow : "none", providers: Object.entries({ openai: "OPENAI_API_KEY", exa: "EXA_API_KEY", brave: "BRAVE_API_KEY", parallel: "PARALLEL_API_KEY", tavily: "TAVILY_API_KEY", perplexity: "PERPLEXITY_API_KEY", gemini: "GEMINI_API_KEY" }).map(([id, env]) => ({ id, has_key: Boolean(stored[id] || process.env[env]), key_source: stored[id] ? "web-access" : process.env[env] ? "environment" : null, env })) }; });
  app.put("/api/settings/web-access", async (request, reply) => { const body = (request.body ?? {}) as { provider?: unknown; workflow?: unknown; api_keys?: unknown; remove_keys?: unknown }; const supported = ["openai", "exa", "brave", "parallel", "tavily", "perplexity", "gemini"]; if (body.api_keys && typeof body.api_keys === "object") for (const key of Object.keys(body.api_keys as Record<string, unknown>)) if (!supported.includes(key)) return reply.code(400).send({ error: `Unknown web search provider: ${key}` }); await mutate((config) => { const web = config.web_access ?? {}; web.provider = String(body.provider ?? "auto"); web.workflow = String(body.workflow ?? "none"); const stored = typeof web.api_keys === "object" && web.api_keys ? web.api_keys as Record<string, string> : {}; if (body.api_keys && typeof body.api_keys === "object") for (const [key, value] of Object.entries(body.api_keys as Record<string, unknown>)) if (String(value).trim()) stored[key] = String(value).trim(); if (Array.isArray(body.remove_keys)) for (const key of body.remove_keys.map(String)) delete stored[key]; web.api_keys = stored; config.web_access = web; }); const response = await app.inject({ method: "GET", url: "/api/settings/web-access" }); return respondWithReload(reply, { ok: true, ...(response.json() as Record<string, unknown>) }); });
  app.get("/api/settings/mcp", async () => { const config = await load(); const source = typeof config.mcp_config_path === "string" ? config.mcp_config_path : configPath("mcp.json"); let definitions: Record<string, unknown> = {}; try { const payload = JSON.parse(await readFile(source, "utf8")) as { mcpServers?: unknown }; definitions = payload.mcpServers && typeof payload.mcpServers === "object" ? payload.mcpServers as Record<string, unknown> : {}; } catch { /* empty catalog */ } const configured = Object.keys(definitions); const enabled = Array.isArray(config.mcp_servers) ? config.mcp_servers.filter((id) => configured.includes(id)) : configured; return { servers: enabled, configured, config_path: source }; });
  app.put<{ Params: { server_id: string } }>("/api/settings/mcp/:server_id", async (request, reply) => { const on = String((request.query as { enabled?: string }).enabled ?? "true") !== "false"; await mutate((config) => { const enabled = new Set(Array.isArray(config.mcp_servers) ? config.mcp_servers : []); if (on) enabled.add(request.params.server_id); else enabled.delete(request.params.server_id); config.mcp_servers = [...enabled].sort(); }); return respondWithReload(reply, { ok: true, server: request.params.server_id, enabled: on }); });
  app.get("/api/settings/skills", async () => { const config = await load(); return { skills: [], configured: Boolean(config.skills_configured) }; });
  app.delete("/api/settings/skills", async (_request, reply) => { await mutate((config) => { delete config.skills_configured; delete config.skill_paths; }); return respondWithReload(reply, { ok: true, message: "Skills reset to auto-discover mode" }); });
  app.get("/api/settings/extensions", async () => ({ extensions: runtimeExtensionStatus() }));
  app.get("/api/settings/subagents", async (request) => { const cwd = query(request, "cwd"); const { readdir } = await import("node:fs/promises"); const { join } = await import("node:path"); const directory = join(cwd, ".pi", "agents"); const agents: unknown[] = []; try { for (const name of await readdir(directory)) if (name.endsWith(".md")) agents.push({ name: name.slice(0, -3), path: join(directory, name) }); } catch { /* no agents */ } return { agents }; });
}

export function endpointId(name: string, baseUrl: string): string { return createHash("sha256").update(`${name}:${baseUrl}`).digest("hex").slice(0, 20); }
