import { StrictMode } from "react";
import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { createMemoryRouter, Outlet, RouterProvider } from "react-router-dom";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { useRuntimeStore } from "../../lib/agent-runtime";
import { FeedbackContext } from "../feedback/feedback-context";
import { WorkspaceSessionList } from "./WorkspaceSessionList";
import { useNewWorkspaceConversation, useWorkspaceSidebar } from "./workspace-navigation";
import { explicitNewLandingState } from "./blank-landing";
import i18n from "../../i18n";
const sessions = [{ id: "s1", cwd: "proj", name: "First" }];
function Shell() { const newConversation = useNewWorkspaceConversation("proj"); return <><button onClick={() => newConversation()}>New</button><WorkspaceSessionList cwd="proj" /><Outlet /></>; }
function mount(entry: string | { pathname: string; state: unknown }, strict = false) { const router = createMemoryRouter([{ element: <Shell />, children: [{ path: "/workspace/proj", element: <span>Blank</span> }, { path: "/workspace/proj/session/:sessionId", element: <span>Session</span> }] }], { initialEntries: [entry] }); const app = <FeedbackContext.Provider value={{ toast: vi.fn(), confirm: async () => true }}><RouterProvider router={router} /></FeedbackContext.Provider>; render(strict ? <StrictMode>{app}</StrictMode> : app); return router; }
beforeEach(async () => { await i18n.changeLanguage("en"); useWorkspaceSidebar.setState({ cwd: "proj", tab: "files", query: "old" }); useRuntimeStore.setState({ cwd: "proj", sessions, sessionsHasMore: false, sessionsLoading: false, activeSessionId: null, loadSessions: vi.fn(async () => sessions), createNewSession: vi.fn(async () => "created") }); });
afterEach(() => cleanup());
it("two consecutive New clicks at root keep blank state and create no session", async () => { const router = mount("/workspace/proj"); fireEvent.click(screen.getByRole("button", { name: "New" })); fireEvent.click(screen.getByRole("button", { name: "New" })); await act(async () => {}); expect(router.state.location.pathname).toBe("/workspace/proj"); expect(router.state.location.state).toEqual({ landingIntent: { kind: "explicit-new", cwd: "proj" } }); expect(router.state.historyAction).toBe("REPLACE"); expect(useWorkspaceSidebar.getState().tab).toBe("sessions"); expect(useWorkspaceSidebar.getState().query).toBe(""); expect(useRuntimeStore.getState().createNewSession).toHaveBeenCalledTimes(0); });
it("a language change cannot auto-open an explicit blank landing", async () => { const router = mount({ pathname: "/workspace/proj", state: explicitNewLandingState("proj") }); await act(async () => { await i18n.changeLanguage("zh-Hans"); }); expect(router.state.location.pathname).toBe("/workspace/proj"); expect(useRuntimeStore.getState().loadSessions).toHaveBeenCalledTimes(0); expect(screen.getByRole("button", { name: "First" })).toBeInTheDocument(); });
it("a session list length change cannot auto-open an explicit blank landing", () => { const router = mount({ pathname: "/workspace/proj", state: explicitNewLandingState("proj") }); act(() => useRuntimeStore.setState({ sessions: [...sessions, { id: "s2", cwd: "proj", name: "Second" }] })); expect(router.state.location.pathname).toBe("/workspace/proj"); expect(useRuntimeStore.getState().loadSessions).toHaveBeenCalledTimes(0); expect(screen.getByRole("button", { name: "First" })).toBeInTheDocument(); });
it("a fresh mount from the same serialized history state keeps an explicit blank landing", () => { const router = mount({ pathname: "/workspace/proj", state: explicitNewLandingState("proj") }); const restored = { pathname: router.state.location.pathname, state: JSON.parse(JSON.stringify(router.state.location.state)) }; cleanup(); const reloaded = mount(restored); expect(reloaded.state.location.pathname).toBe("/workspace/proj"); expect(useRuntimeStore.getState().loadSessions).toHaveBeenCalledTimes(0); expect(screen.getByRole("button", { name: "First" })).toBeInTheDocument(); });
it("StrictMode effect restart and remount keep an explicit blank landing", () => { const entry = { pathname: "/workspace/proj", state: explicitNewLandingState("proj") }; const router = mount(entry, true); expect(router.state.location.pathname).toBe("/workspace/proj"); cleanup(); const remounted = mount(entry, true); expect(remounted.state.location.pathname).toBe("/workspace/proj"); expect(useRuntimeStore.getState().loadSessions).toHaveBeenCalledTimes(0); expect(screen.getByRole("button", { name: "First" })).toBeInTheDocument(); });
it("a normal root entry auto-opens the most recent existing session", async () => { const router = mount("/workspace/proj"); await waitFor(() => expect(router.state.location.pathname).toBe("/workspace/proj/session/s1")); expect(useRuntimeStore.getState().loadSessions).toHaveBeenCalledTimes(1); });
