import { act, cleanup, fireEvent, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { createMemoryRouter, RouterProvider } from "react-router-dom";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { ProjectsLayout } from "../../app/layout/ProjectsLayout";
import { WorkspaceProvider } from "../../lib/workspace";
import { useRuntimeStore } from "../../lib/agent-runtime";
import { useUiStore } from "../../lib/ui";
import { FeedbackContext } from "../feedback/feedback-context";
import { useWorkspaceSidebar } from "./workspace-navigation";
import i18n from "../../i18n";
import type { FileListEntry } from "./FileContextMenu";
const entry = (name: string, path = name, isDir = true): FileListEntry => ({ name, path, isDir, size: 0, modified: 1 });
const files = vi.hoisted(() => ({ sidebar: vi.fn(), directory: vi.fn(), invalidate: vi.fn() }));
vi.mock("../../lib/workspace", async importOriginal => ({ ...await importOriginal<typeof import("../../lib/workspace")>(), workspaceFiles: files }));
vi.mock("../../lib/knowledge", () => ({ usePendingProposalCount: () => ({ data: { pending_count: 0 } }) }));
vi.mock("../inspector/InspectorTabs", () => ({ InspectorTabs: () => null }));
const feedback = { toast: vi.fn(), confirm: vi.fn(async () => true) };
let narrow = false;
let listeners = new Set<(event: MediaQueryListEvent) => void>();
function resize(width: number) { act(() => { vi.stubGlobal("innerWidth", width); narrow = width < 768; for (const listener of listeners) listener({ matches: narrow } as MediaQueryListEvent); }); }
function mount() { const router = createMemoryRouter([{ element: <WorkspaceProvider><ProjectsLayout /></WorkspaceProvider>, children: [{ path: "/workspace/:cwd/research", element: <span>Main Research</span> }, { path: "/workspace/:cwd/runs", element: <span>Main Runs</span> }] }], { initialEntries: ["/workspace/proj/research"] }); const view = render(<FeedbackContext.Provider value={feedback}><RouterProvider router={router} /></FeedbackContext.Provider>); return { ...view, router }; }
beforeEach(async () => { await i18n.changeLanguage("en"); narrow = false; listeners = new Set(); vi.stubGlobal("innerWidth", 1280); vi.stubGlobal("matchMedia", (query: string) => ({ get matches() { return query.includes("767") && narrow; }, media: query, addEventListener: (_type: string, listener: (event: MediaQueryListEvent) => void) => { if (query.includes("767")) listeners.add(listener); }, removeEventListener: (_type: string, listener: (event: MediaQueryListEvent) => void) => listeners.delete(listener) })); Object.defineProperty(document, "visibilityState", { value: "visible", configurable: true }); useUiStore.setState({ contextPanelCollapsed: false, sidebarWidth: 299, inspectorOpen: false, inspectorTabs: [], settingsOpen: false }); useWorkspaceSidebar.setState({ cwd: null, tab: "sessions", query: "" }); useRuntimeStore.setState({ cwd: "proj", sessions: [{ id: "a", cwd: "proj", name: "Loaded A" }], activeSessionId: "a", sessionsHasMore: true, sessionsLoading: false, loadSessions: vi.fn(async () => []), fileRevision: 0 }); files.sidebar.mockReset().mockImplementation(async (cwd: string) => [entry(cwd === "proj" ? "work" : "B folder")]); files.directory.mockReset().mockImplementation(async (_cwd: string, dir: string) => ({ entries: dir === "work" ? [entry("experiments", "work/experiments")] : [entry("result.txt", "work/experiments/result.txt", false)], breadcrumbs: [] })); });
afterEach(() => { cleanup(); vi.unstubAllGlobals(); });
it("keeps session DOM and scroll plus nested file folders across tabs, collapse, routes and breakpoint crossings", async () => { const { container, router } = mount(); const row = await screen.findByRole("button", { name: "Loaded A" }); const list = row.closest("div[aria-label='Conversations']") ?? row.closest(".overflow-y-auto")!; list.scrollTop = 73; const panel = container.querySelector("aside")!; fireEvent.change(screen.getByRole("searchbox"), { target: { value: "Loaded" } }); await userEvent.click(screen.getByRole("tab", { name: "Files" })); await userEvent.click(await screen.findByRole("button", { name: "experiments" })); const file = await screen.findByRole("button", { name: "result.txt" }); const tree = file.closest(".overflow-y-auto")!; tree.scrollTop = 41; await act(async () => router.navigate("/workspace/proj/runs")); expect(screen.getByRole("tab", { name: "Files" })).toHaveAttribute("aria-selected", "true"); expect(screen.getByRole("link", { name: "Run history" })).toHaveAttribute("aria-current", "page"); fireEvent.click(screen.getByRole("button", { name: "Workspace context panel" })); expect(panel).toHaveAttribute("hidden"); expect(row).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Workspace context panel" })); expect(screen.getByRole("button", { name: "result.txt" })).toBe(file); expect(tree.scrollTop).toBe(41); await userEvent.click(screen.getByRole("tab", { name: "Conversations" })); expect(screen.getByRole("button", { name: "Loaded A" })).toBe(row); expect(list.scrollTop).toBe(73); expect(screen.getByRole("searchbox")).toHaveValue("Loaded"); resize(767); expect(panel).toHaveAttribute("hidden"); fireEvent.click(screen.getByRole("button", { name: "Workspace context panel" })); expect(container.querySelector("aside")).toBe(panel); expect(screen.getByRole("button", { name: "Loaded A" })).toBe(row); expect(list.scrollTop).toBe(73); resize(768); expect(panel).not.toHaveAttribute("hidden"); await userEvent.click(screen.getByRole("tab", { name: "Files" })); expect(screen.getByRole("button", { name: "result.txt" })).toBe(file); expect(tree.scrollTop).toBe(41); expect(useRuntimeStore.getState().loadSessions).toHaveBeenCalledTimes(0); });
it("workspace switch hides all old rows, pagination, folders and late request results", async () => { const { router } = mount(); await screen.findByRole("button", { name: "Loaded A" }); await userEvent.click(screen.getByRole("tab", { name: "Files" })); await userEvent.click(await screen.findByRole("button", { name: "experiments" })); await screen.findByRole("button", { name: "result.txt" }); let resolve!: (items: FileListEntry[]) => void; files.sidebar.mockImplementationOnce(() => new Promise<FileListEntry[]>(r => { resolve = r; })); fireEvent.click(screen.getByRole("button", { name: "Refresh files" })); await act(async () => router.navigate("/workspace/other/research")); expect(screen.queryByRole("button", { name: "Loaded A", hidden: true })).toBe(null); expect(screen.queryByRole("button", { name: "Load older conversations" })).toBe(null); expect(screen.queryByText("experiments")).toBe(null); expect(screen.queryByText("result.txt")).toBe(null); expect(screen.getByRole("searchbox")).toHaveValue(""); await userEvent.click(screen.getByRole("tab", { name: "Files" })); await screen.findByRole("button", { name: "B folder" }); await act(async () => resolve([entry("A stale")])); expect(screen.queryByText("A stale")).toBe(null); expect(screen.queryByText("work")).toBe(null); expect(screen.getByRole("button", { name: "B folder" })).toHaveAttribute("title", "B folder"); act(() => useRuntimeStore.setState({ cwd: "other", sessions: [{ id: "b", cwd: "other", name: "Loaded B" }], activeSessionId: null, sessionsHasMore: false })); await userEvent.click(screen.getByRole("tab", { name: "Conversations" })); expect(screen.getByRole("button", { name: "Loaded B" })).toBeInTheDocument(); expect(screen.queryByRole("button", { name: "Loaded A", hidden: true })).toBe(null); });
