#!/usr/bin/env bash
# Credential-free launcher contract and lifecycle tests for POSIX CI.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
START_SCRIPT="$PROJECT_DIR/scripts/start.sh"
INSTALL_SCRIPT="$PROJECT_DIR/scripts/install.sh"
WRITER_SCRIPT="$PROJECT_DIR/scripts/write-launcher.sh"
TEMP_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/pi science launcher.XXXXXX")"
START_PID=""
cleanup() { [ -z "$START_PID" ] || kill "$START_PID" 2>/dev/null || true; rm -rf "$TEMP_ROOT"; }
trap cleanup EXIT

fail() { echo "launcher test failed: $*" >&2; exit 1; }
assert_contains() { grep -Fq "$2" "$1" || fail "$1 does not contain: $2"; }
assert_not_contains() { ! grep -Fq "$2" "$1" || fail "$1 unexpectedly contains: $2"; }
free_port() { python3 -c 'import socket; s=socket.socket(); s.bind(("127.0.0.1", 0)); print(s.getsockname()[1]); s.close()'; }
port_available() { python3 -c 'import socket,sys; s=socket.socket(); s.setsockopt(socket.SOL_SOCKET,socket.SO_REUSEADDR,1); s.bind(("127.0.0.1",int(sys.argv[1]))); s.close()' "$1"; }
wait_url() { local url="$1" attempts=100; while [ "$attempts" -gt 0 ]; do curl --fail --silent "$url" >/dev/null 2>&1 && return 0; sleep 0.1; attempts=$((attempts - 1)); done; return 1; }
wait_port_available() { local port="$1" attempts=100; while [ "$attempts" -gt 0 ]; do port_available "$port" >/dev/null 2>&1 && return 0; sleep 0.1; attempts=$((attempts - 1)); done; return 1; }

# Static contract: package-local executables, preserved CWD, no package-manager
# wrapper, actionable diagnostics, and the shared readiness deadline.
assert_contains "$START_SCRIPT" 'apps/server/node_modules/tsx/dist/cli.mjs'
assert_contains "$START_SCRIPT" 'frontend/node_modules/.bin/vite'
assert_contains "$START_SCRIPT" 'cd "$PROJECT_DIR/apps/server"'
assert_contains "$START_SCRIPT" 'cd "$PROJECT_DIR/frontend"'
assert_contains "$START_SCRIPT" 'Run: bash scripts/install.sh'
assert_contains "$START_SCRIPT" 'PI_SCIENCE_STARTUP_TIMEOUT_SECONDS'
assert_not_contains "$START_SCRIPT" 'npm run dev'
assert_not_contains "$START_SCRIPT" 'pnpm --config.store-dir'
assert_contains "$INSTALL_SCRIPT" 'write-launcher.sh'
assert_contains "$PROJECT_DIR/package.json" '"node": ">=22.12.0"'

# PATH launcher installation: checkout paths with spaces, owned reinstall,
# legacy-owned migration, and refusal of unrelated/symlink/directory entries.
CHECKOUT="$TEMP_ROOT/checkout with spaces"
BIN_DIR="$TEMP_ROOT/bin with spaces"
mkdir -p "$CHECKOUT/scripts" "$BIN_DIR"
cp "$PROJECT_DIR/scripts/pi-science.sh" "$CHECKOUT/scripts/pi-science.sh"
bash "$WRITER_SCRIPT" "$CHECKOUT" "$BIN_DIR"
LAUNCHER="$BIN_DIR/pi-science"
[ -x "$LAUNCHER" ] || fail "generated launcher is not executable"
assert_contains "$LAUNCHER" '# pi-science-launcher-v1'
assert_contains "$LAUNCHER" 'checkout\ with\ spaces'
bash "$WRITER_SCRIPT" "$CHECKOUT" "$BIN_DIR"
assert_contains "$LAUNCHER" '# pi-science-launcher-v1'
rm -f "$LAUNCHER"
printf '#!/usr/bin/env bash\n# Generated by scripts/install.sh. Re-run it if this checkout moves.\nPI_SCIENCE_DIR=%q\nexec bash "$PI_SCIENCE_DIR/scripts/pi-science.sh" "$@"\n' "$CHECKOUT" > "$LAUNCHER"
bash "$WRITER_SCRIPT" "$CHECKOUT" "$BIN_DIR"
assert_contains "$LAUNCHER" '# pi-science-launcher-v1'
printf 'unrelated\n' > "$LAUNCHER"
if bash "$WRITER_SCRIPT" "$CHECKOUT" "$BIN_DIR" >"$TEMP_ROOT/collision.log" 2>&1; then fail "unrelated launcher was overwritten"; fi
assert_contains "$LAUNCHER" 'unrelated'
assert_contains "$TEMP_ROOT/collision.log" 'refusing to overwrite unrelated launcher path'
rm -f "$LAUNCHER"
printf 'target-data\n' > "$TEMP_ROOT/target"
ln -s "$TEMP_ROOT/target" "$LAUNCHER"
if bash "$WRITER_SCRIPT" "$CHECKOUT" "$BIN_DIR" >/dev/null 2>&1; then fail "launcher symlink was overwritten"; fi
assert_contains "$TEMP_ROOT/target" 'target-data'
rm -f "$LAUNCHER"
mkdir "$LAUNCHER"
if bash "$WRITER_SCRIPT" "$CHECKOUT" "$BIN_DIR" >/dev/null 2>&1; then fail "launcher directory was overwritten"; fi
rm -rf "$LAUNCHER"

# Temporary local checkout with real Node and fake package-local CLIs. The fake
# services record CWD/PIDs and expose only the readiness endpoints used by start.sh.
FIXTURE="$TEMP_ROOT/runtime checkout with spaces"
mkdir -p "$FIXTURE/scripts" "$FIXTURE/apps/server/node_modules/tsx/dist" "$FIXTURE/frontend/node_modules/.bin" "$FIXTURE/frontend"
cp "$START_SCRIPT" "$FIXTURE/scripts/start.sh"
printf '// fake Pi CLI\n' > "$FIXTURE/pi-cli.mjs"
cat > "$FIXTURE/apps/server/node_modules/tsx/dist/cli.mjs" <<'EOF'
import { spawn } from "node:child_process";
import { writeFileSync } from "node:fs";
import http from "node:http";
writeFileSync(new URL("../../../../../control.cwd", import.meta.url), process.cwd());
writeFileSync(new URL("../../../../../control.pid", import.meta.url), String(process.pid));
const child = spawn(process.execPath, ["-e", "setInterval(() => {}, 1000)"], { stdio: "ignore" });
writeFileSync(new URL("../../../../../control.child.pid", import.meta.url), String(child.pid));
const server = http.createServer((req, res) => { res.writeHead(req.url === "/api/health" ? 200 : 404); res.end("ok"); });
server.listen(Number(process.env.PI_SCIENCE_PORT), "127.0.0.1");
const stop = () => { child.kill("SIGTERM"); server.close(() => process.exit(0)); setTimeout(() => process.exit(0), 500).unref(); };
process.on("SIGTERM", stop); process.on("SIGINT", stop);
EOF
cat > "$FIXTURE/frontend/fake-vite.mjs" <<'EOF'
import { writeFileSync } from "node:fs";
import http from "node:http";
const args = process.argv.slice(2); const port = Number(args[args.indexOf("--port") + 1]);
writeFileSync(new URL("../frontend.cwd", import.meta.url), process.cwd());
writeFileSync(new URL("../frontend.pid", import.meta.url), String(process.pid));
const server = http.createServer((_req, res) => { res.writeHead(200); res.end("vite"); });
server.listen(port, "127.0.0.1");
const stop = () => server.close(() => process.exit(0));
process.on("SIGTERM", stop); process.on("SIGINT", stop);
EOF
cat > "$FIXTURE/frontend/node_modules/.bin/vite" <<EOF
#!/usr/bin/env bash
exec "$(command -v node)" "$FIXTURE/frontend/fake-vite.mjs" "\$@"
EOF
chmod +x "$FIXTURE/frontend/node_modules/.bin/vite"

CONTROL_PORT="$(free_port)"
RUNTIME_PORT="$(free_port)"
FRONTEND_PORT="$(free_port)"
LOG="$TEMP_ROOT/start.log"
PI_SCIENCE_PYTHON="$(command -v python3)" PI_CLI_PATH="$FIXTURE/pi-cli.mjs" PI_SCIENCE_CONTROL_PLANE_PORT="$CONTROL_PORT" PI_SCIENCE_RUNTIME_PORT="$RUNTIME_PORT" PI_SCIENCE_FRONTEND_PORT="$FRONTEND_PORT" PI_SCIENCE_STARTUP_TIMEOUT_SECONDS=10 bash "$FIXTURE/scripts/start.sh" >"$LOG" 2>&1 &
START_PID=$!
wait_url "http://127.0.0.1:$CONTROL_PORT/api/health" || { cat "$LOG" >&2; fail "control plane did not become ready"; }
wait_url "http://127.0.0.1:$FRONTEND_PORT" || { cat "$LOG" >&2; fail "frontend did not become ready"; }
FIXTURE_CANONICAL="$(cd "$FIXTURE" && pwd -P)"
[ "$(cat "$FIXTURE/control.cwd")" = "$FIXTURE_CANONICAL/apps/server" ] || fail "control plane CWD changed"
[ "$(cat "$FIXTURE/frontend.cwd")" = "$FIXTURE_CANONICAL/frontend" ] || fail "frontend CWD changed"
CONTROL_PID="$(cat "$FIXTURE/control.pid")"; CONTROL_CHILD_PID="$(cat "$FIXTURE/control.child.pid")"; FRONTEND_PID="$(cat "$FIXTURE/frontend.pid")"
kill -TERM "$START_PID"
wait "$START_PID" 2>/dev/null || true
START_PID=""
wait_port_available "$CONTROL_PORT" || fail "control-plane port was not released"
wait_port_available "$FRONTEND_PORT" || fail "frontend port was not released"
! kill -0 "$CONTROL_PID" 2>/dev/null || fail "control plane survived cleanup"
! kill -0 "$CONTROL_CHILD_PID" 2>/dev/null || fail "control-plane descendant survived cleanup"
! kill -0 "$FRONTEND_PID" 2>/dev/null || fail "frontend survived cleanup"

# A frontend startup failure must clean up the already-ready control plane.
cat > "$FIXTURE/frontend/node_modules/.bin/vite" <<'EOF'
#!/usr/bin/env bash
exit 7
EOF
chmod +x "$FIXTURE/frontend/node_modules/.bin/vite"
FAIL_PORT="$(free_port)"
if PI_SCIENCE_PYTHON="$(command -v python3)" PI_CLI_PATH="$FIXTURE/pi-cli.mjs" PI_SCIENCE_CONTROL_PLANE_PORT="$FAIL_PORT" PI_SCIENCE_RUNTIME_PORT="$(free_port)" PI_SCIENCE_FRONTEND_PORT="$(free_port)" PI_SCIENCE_STARTUP_TIMEOUT_SECONDS=3 bash "$FIXTURE/scripts/start.sh" >"$TEMP_ROOT/failure.log" 2>&1; then fail "frontend startup failure returned success"; fi
wait_port_available "$FAIL_PORT" || fail "startup failure left the control-plane port occupied"
assert_contains "$TEMP_ROOT/failure.log" 'frontend exited during startup'

# Missing package-local dependency fails before starting either service.
rm -f "$FIXTURE/frontend/node_modules/.bin/vite"
if PI_SCIENCE_PYTHON="$(command -v python3)" PI_CLI_PATH="$FIXTURE/pi-cli.mjs" bash "$FIXTURE/scripts/start.sh" >"$TEMP_ROOT/missing.log" 2>&1; then fail "missing Vite dependency returned success"; fi
assert_contains "$TEMP_ROOT/missing.log" 'frontend dependencies are not installed. Run: bash scripts/install.sh'

echo "launcher contract and lifecycle tests passed"
