#!/usr/bin/env bash
# Credential-free launcher contract and lifecycle tests for POSIX CI.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
START_SCRIPT="$PROJECT_DIR/scripts/start.sh"
COMMAND_SCRIPT="$PROJECT_DIR/scripts/pi-science.sh"
NODE_CHECK_SCRIPT="$PROJECT_DIR/scripts/check-node-version.mjs"
NODE_RUNTIME_SCRIPT="$PROJECT_DIR/scripts/node-runtime.sh"
INSTALL_SCRIPT="$PROJECT_DIR/scripts/install.sh"
WRITER_SCRIPT="$PROJECT_DIR/scripts/write-launcher.sh"
TEMP_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/pi science launcher.XXXXXX")"
START_PID=""
cleanup() { [ -z "$START_PID" ] || kill "$START_PID" 2>/dev/null || true; rm -rf "$TEMP_ROOT"; }
trap cleanup EXIT

fail() { echo "launcher test failed: $*" >&2; exit 1; }
assert_contains() { grep -Fq "$2" "$1" || fail "$1 does not contain: $2"; }
assert_not_contains() { ! grep -Fq "$2" "$1" || fail "$1 unexpectedly contains: $2"; }
free_port() { python3 -c 'import socket; s=socket.socket(); s.bind(("127.0.0.1", 0)); print(s.getsockname()[1]); s.close()'; }
port_available() { python3 -c 'import socket,sys; s=socket.socket(); s.setsockopt(socket.SOL_SOCKET,socket.SO_REUSEADDR,1); s.bind(("127.0.0.1",int(sys.argv[1]))); s.close()' "$1"; }
wait_url() { local url="$1" attempts=100; while [ "$attempts" -gt 0 ]; do curl --fail --silent "$url" >/dev/null 2>&1 && return 0; sleep 0.1; attempts=$((attempts - 1)); done; return 1; }
wait_port_available() { local port="$1" attempts=100; while [ "$attempts" -gt 0 ]; do port_available "$port" >/dev/null 2>&1 && return 0; sleep 0.1; attempts=$((attempts - 1)); done; return 1; }
wait_file() { local file="$1" attempts=200; while [ "$attempts" -gt 0 ]; do [ -f "$file" ] && return 0; sleep 0.05; attempts=$((attempts - 1)); done; return 1; }
wait_pid_gone() { local pid="$1" attempts=100; while [ "$attempts" -gt 0 ]; do ! kill -0 "$pid" 2>/dev/null && return 0; sleep 0.1; attempts=$((attempts - 1)); done; return 1; }

if node "$NODE_CHECK_SCRIPT" 24.15.0; then fail "Node 24.15 was accepted"; fi
node "$NODE_CHECK_SCRIPT" 24.16.0 || fail "Node 24.16 was rejected"
node "$NODE_CHECK_SCRIPT" 25.0.0 || fail "Node 25 was rejected"

# Static contract: package-local executables, preserved CWD, no package-manager
# wrapper, actionable diagnostics, and the shared readiness deadline.
assert_contains "$START_SCRIPT" 'apps/server/node_modules/tsx/dist/cli.mjs'
assert_contains "$START_SCRIPT" 'frontend/node_modules/.bin/vite'
assert_contains "$START_SCRIPT" 'cd "$PROJECT_DIR/apps/server"'
assert_contains "$START_SCRIPT" 'cd "$PROJECT_DIR/frontend"'
assert_contains "$START_SCRIPT" 'Run: bash scripts/install.sh'
assert_contains "$START_SCRIPT" 'PI_SCIENCE_STARTUP_TIMEOUT_SECONDS'
assert_contains "$START_SCRIPT" 'node-runtime.sh'
assert_contains "$NODE_RUNTIME_SCRIPT" 'check-node-version.mjs'
assert_not_contains "$START_SCRIPT" 'npm run dev'
assert_not_contains "$START_SCRIPT" 'pnpm --config.store-dir'
assert_contains "$INSTALL_SCRIPT" 'write-launcher.sh'
assert_contains "$PROJECT_DIR/package.json" '"node": ">=24.16.0"'

# PATH launcher installation: checkout paths with spaces, owned reinstall,
# legacy-owned migration, and refusal of unrelated/symlink/directory entries.
CHECKOUT="$TEMP_ROOT/checkout with spaces"
BIN_DIR="$TEMP_ROOT/bin with spaces"
mkdir -p "$CHECKOUT/scripts" "$BIN_DIR"
cp "$PROJECT_DIR/scripts/pi-science.sh" "$CHECKOUT/scripts/pi-science.sh"
cp "$NODE_RUNTIME_SCRIPT" "$CHECKOUT/scripts/node-runtime.sh"
bash "$WRITER_SCRIPT" "$CHECKOUT" "$BIN_DIR"
LAUNCHER="$BIN_DIR/pi-science"
[ -x "$LAUNCHER" ] || fail "generated launcher is not executable"
assert_contains "$LAUNCHER" '# pi-science-launcher-v1'
assert_contains "$LAUNCHER" 'checkout\ with\ spaces'
bash "$WRITER_SCRIPT" "$CHECKOUT" "$BIN_DIR"
assert_contains "$LAUNCHER" '# pi-science-launcher-v1'
bash "$LAUNCHER" help >"$TEMP_ROOT/generated-launcher.log"
assert_contains "$TEMP_ROOT/generated-launcher.log" 'Scientific AI Workbench'
rm -f "$LAUNCHER"
printf '#!/usr/bin/env bash\n# Generated by scripts/install.sh. Re-run it if this checkout moves.\nPI_SCIENCE_DIR=%q\nexec bash "$PI_SCIENCE_DIR/scripts/pi-science.sh" "$@"\n' "$CHECKOUT" > "$LAUNCHER"
bash "$WRITER_SCRIPT" "$CHECKOUT" "$BIN_DIR"
assert_contains "$LAUNCHER" '# pi-science-launcher-v1'
printf 'unrelated\n' > "$LAUNCHER"
if bash "$WRITER_SCRIPT" "$CHECKOUT" "$BIN_DIR" >"$TEMP_ROOT/collision.log" 2>&1; then fail "unrelated launcher was overwritten"; fi
assert_contains "$LAUNCHER" 'unrelated'
assert_contains "$TEMP_ROOT/collision.log" 'refusing to overwrite unrelated launcher path'
rm -f "$LAUNCHER"
printf 'target-data\n' > "$TEMP_ROOT/target"
ln -s "$TEMP_ROOT/target" "$LAUNCHER"
if bash "$WRITER_SCRIPT" "$CHECKOUT" "$BIN_DIR" >/dev/null 2>&1; then fail "launcher symlink was overwritten"; fi
assert_contains "$TEMP_ROOT/target" 'target-data'
rm -f "$LAUNCHER"
mkdir "$LAUNCHER"
if bash "$WRITER_SCRIPT" "$CHECKOUT" "$BIN_DIR" >/dev/null 2>&1; then fail "launcher directory was overwritten"; fi
rm -rf "$LAUNCHER"
OTHER_CHECKOUT="$TEMP_ROOT/other checkout"
mkdir -p "$OTHER_CHECKOUT/scripts"
cp "$PROJECT_DIR/scripts/pi-science.sh" "$OTHER_CHECKOUT/scripts/pi-science.sh"
cp "$NODE_RUNTIME_SCRIPT" "$OTHER_CHECKOUT/scripts/node-runtime.sh"
bash "$WRITER_SCRIPT" "$OTHER_CHECKOUT" "$BIN_DIR"
if bash "$WRITER_SCRIPT" "$CHECKOUT" "$BIN_DIR" >"$TEMP_ROOT/other-checkout.log" 2>&1; then fail "another checkout's owned launcher was overwritten"; fi
assert_contains "$TEMP_ROOT/other-checkout.log" 'refusing to overwrite unrelated launcher path'
rm -f "$LAUNCHER"

# A destination substituted after initial validation is detected before commit.
for kind in file directory; do
  BARRIER="$TEMP_ROOT/barrier-$kind"
  rm -f "$LAUNCHER" "$BARRIER.ready" "$BARRIER.release"
  rm -rf "$LAUNCHER"
  PI_SCIENCE_TEST_LAUNCHER_COMMIT_BARRIER="$BARRIER" bash "$WRITER_SCRIPT" "$CHECKOUT" "$BIN_DIR" >"$TEMP_ROOT/race-$kind.log" 2>&1 &
  WRITER_PID=$!
  wait_file "$BARRIER.ready" || fail "$kind race barrier was not reached"
  if [ "$kind" = file ]; then printf 'racer-data\n' > "$LAUNCHER"; else mkdir "$LAUNCHER"; fi
  : > "$BARRIER.release"
  if wait "$WRITER_PID"; then fail "$kind substitution was silently accepted"; fi
  if [ "$kind" = file ]; then assert_contains "$LAUNCHER" 'racer-data'; rm -f "$LAUNCHER"; else [ -d "$LAUNCHER" ] || fail "racing directory was replaced"; rm -rf "$LAUNCHER"; fi
  assert_contains "$TEMP_ROOT/race-$kind.log" 'refusing to overwrite unrelated launcher path'
  [ ! -d "$BIN_DIR/.pi-science-launcher.lock" ] || fail "installer lock leaked after $kind race"
  if find "$BIN_DIR" -maxdepth 1 -name '.pi-science-launcher.*' -print | grep -q .; then fail "installer temp file leaked after $kind race"; fi
done

# A failed second/third writer never removes the first writer's lock.
CONTENTION_BARRIER="$TEMP_ROOT/contention"
rm -f "$LAUNCHER" "$CONTENTION_BARRIER.ready" "$CONTENTION_BARRIER.release"
PI_SCIENCE_TEST_LAUNCHER_COMMIT_BARRIER="$CONTENTION_BARRIER" bash "$WRITER_SCRIPT" "$CHECKOUT" "$BIN_DIR" >"$TEMP_ROOT/writer-1.log" 2>&1 &
WRITER_ONE_PID=$!
wait_file "$CONTENTION_BARRIER.ready" || fail "first writer did not reach contention barrier"
[ -d "$BIN_DIR/.pi-science-launcher.lock" ] || fail "first writer does not own the lock"
if bash "$WRITER_SCRIPT" "$CHECKOUT" "$BIN_DIR" >"$TEMP_ROOT/writer-2.log" 2>&1; then fail "second writer acquired an owned lock"; fi
[ -d "$BIN_DIR/.pi-science-launcher.lock" ] || fail "second writer removed the first writer's lock"
if bash "$WRITER_SCRIPT" "$CHECKOUT" "$BIN_DIR" >"$TEMP_ROOT/writer-3.log" 2>&1; then fail "third writer acquired an owned lock"; fi
[ -d "$BIN_DIR/.pi-science-launcher.lock" ] || fail "third writer removed the first writer's lock"
: > "$CONTENTION_BARRIER.release"
wait "$WRITER_ONE_PID" || fail "first writer failed after contention"
[ ! -e "$BIN_DIR/.pi-science-launcher.lock" ] || fail "first writer leaked its lock"

# TERM exits a blocked writer and cleans exactly the lock/temp files it owns.
SIGNAL_BARRIER="$TEMP_ROOT/signaled-writer"
rm -f "$LAUNCHER" "$SIGNAL_BARRIER.ready" "$SIGNAL_BARRIER.release"
PI_SCIENCE_TEST_LAUNCHER_COMMIT_BARRIER="$SIGNAL_BARRIER" bash "$WRITER_SCRIPT" "$CHECKOUT" "$BIN_DIR" >"$TEMP_ROOT/signaled-writer.log" 2>&1 &
SIGNALED_WRITER_PID=$!
wait_file "$SIGNAL_BARRIER.ready" || fail "signaled writer did not reach barrier"
kill -TERM "$SIGNALED_WRITER_PID"
set +e
wait "$SIGNALED_WRITER_PID"; SIGNALED_STATUS=$?
set -e
[ "$SIGNALED_STATUS" -eq 143 ] || fail "signaled writer exited $SIGNALED_STATUS instead of 143"
[ ! -e "$BIN_DIR/.pi-science-launcher.lock" ] || fail "signaled writer leaked its lock"
if find "$BIN_DIR" -maxdepth 1 -name '.pi-science-launcher.*' -print | grep -q .; then fail "signaled writer leaked a temp file"; fi

# Temporary local checkout with real Node and fake package-local CLIs. The fake
# services record CWD/PIDs and expose only the readiness endpoints used by start.sh.
FIXTURE="$TEMP_ROOT/runtime checkout with spaces"
mkdir -p "$FIXTURE/scripts" "$FIXTURE/apps/server/node_modules/tsx/dist" "$FIXTURE/frontend/node_modules/.bin" "$FIXTURE/frontend"
cp "$START_SCRIPT" "$FIXTURE/scripts/start.sh"
cp "$COMMAND_SCRIPT" "$FIXTURE/scripts/pi-science.sh"
cp "$NODE_CHECK_SCRIPT" "$FIXTURE/scripts/check-node-version.mjs"
cp "$NODE_RUNTIME_SCRIPT" "$FIXTURE/scripts/node-runtime.sh"
printf '// fake Pi CLI\n' > "$FIXTURE/pi-cli.mjs"
cat > "$FIXTURE/apps/server/node_modules/tsx/dist/cli.mjs" <<'EOF'
import { spawn } from "node:child_process";
import { writeFileSync } from "node:fs";
import http from "node:http";
writeFileSync(new URL("../../../../../control.cwd", import.meta.url), process.cwd());
writeFileSync(new URL("../../../../../control.pid", import.meta.url), String(process.pid));
writeFileSync(new URL("../../../../../control.argv", import.meta.url), JSON.stringify(process.argv.slice(2)));
writeFileSync(new URL("../../../../../control.open-browser", import.meta.url), process.env.PI_SCIENCE_OPEN_BROWSER ?? "");
const child = spawn(process.execPath, ["-e", "process.on('SIGTERM',()=>{}); setInterval(() => {}, 1000)"], { stdio: "ignore" });
writeFileSync(new URL("../../../../../control.child.pid", import.meta.url), String(child.pid));
const server = http.createServer((req, res) => {
  const ready = req.url === "/api/health" || req.url === "/internal/ready";
  res.writeHead(ready ? 200 : 404);
  res.end("ok");
});
setTimeout(() => server.listen(Number(process.env.PI_SCIENCE_PORT), "127.0.0.1"), Number(process.env.PI_SCIENCE_TEST_CONTROL_DELAY_MS || 0));
const stop = () => { child.kill("SIGTERM"); server.close(() => process.exit(0)); setTimeout(() => process.exit(0), 500).unref(); };
process.on("SIGTERM", stop); process.on("SIGINT", stop);
EOF
cat > "$FIXTURE/frontend/fake-vite.mjs" <<'EOF'
import { writeFileSync } from "node:fs";
import http from "node:http";
const args = process.argv.slice(2); const port = Number(args[args.indexOf("--port") + 1]);
writeFileSync(new URL("../frontend.cwd", import.meta.url), process.cwd());
writeFileSync(new URL("../frontend.pid", import.meta.url), String(process.pid));
const server = http.createServer((_req, res) => { res.writeHead(200); res.end("vite"); });
if (process.env.PI_SCIENCE_TEST_FRONTEND_NEVER_READY !== "1") setTimeout(() => server.listen(port, "127.0.0.1"), Number(process.env.PI_SCIENCE_TEST_FRONTEND_DELAY_MS || 0));
else setInterval(() => {}, 1000);
const stop = () => server.close(() => process.exit(0));
process.on("SIGTERM", stop); process.on("SIGINT", stop);
EOF
cat > "$FIXTURE/frontend/node_modules/.bin/vite" <<EOF
#!/usr/bin/env bash
exec "$(command -v node)" "$FIXTURE/frontend/fake-vite.mjs" "\$@"
EOF
chmod +x "$FIXTURE/frontend/node_modules/.bin/vite"

CONTROL_PORT="$(free_port)"
RUNTIME_PORT="$(free_port)"
FRONTEND_PORT="$(free_port)"
LOG="$TEMP_ROOT/start.log"
PI_SCIENCE_PYTHON="$(command -v python3)" PI_CLI_PATH="$FIXTURE/pi-cli.mjs" PI_SCIENCE_CONTROL_PLANE_PORT="$CONTROL_PORT" PI_SCIENCE_RUNTIME_PORT="$RUNTIME_PORT" PI_SCIENCE_FRONTEND_PORT="$FRONTEND_PORT" PI_SCIENCE_STARTUP_TIMEOUT_SECONDS=10 bash "$FIXTURE/scripts/start.sh" >"$LOG" 2>&1 &
START_PID=$!
wait_url "http://127.0.0.1:$CONTROL_PORT/internal/ready" || { cat "$LOG" >&2; fail "control plane did not become ready"; }
wait_url "http://127.0.0.1:$FRONTEND_PORT" || { cat "$LOG" >&2; fail "frontend did not become ready"; }
FIXTURE_CANONICAL="$(cd "$FIXTURE" && pwd -P)"
[ "$(cat "$FIXTURE/control.cwd")" = "$FIXTURE_CANONICAL/apps/server" ] || fail "control plane CWD changed"
[ "$(cat "$FIXTURE/frontend.cwd")" = "$FIXTURE_CANONICAL/frontend" ] || fail "frontend CWD changed"
[ "$(cat "$FIXTURE/control.argv")" = '["src/app/main.ts"]' ] || fail "default control plane argv is not direct mode: $(cat "$FIXTURE/control.argv")"
[ "$(cat "$FIXTURE/control.open-browser")" = '0' ] || fail "control plane inherited browser-open ownership from the frontend launcher"
assert_contains "$LOG" 'control plane mode: stable'
assert_not_contains "$LOG" 'control plane mode: watch'
CONTROL_PID="$(cat "$FIXTURE/control.pid")"; CONTROL_CHILD_PID="$(cat "$FIXTURE/control.child.pid")"; FRONTEND_PID="$(cat "$FIXTURE/frontend.pid")"
kill -TERM "$START_PID"
wait "$START_PID" 2>/dev/null || true
START_PID=""
wait_port_available "$CONTROL_PORT" || fail "control-plane port was not released"
wait_port_available "$FRONTEND_PORT" || fail "frontend port was not released"
wait_pid_gone "$CONTROL_PID" || fail "control plane survived cleanup"
wait_pid_gone "$CONTROL_CHILD_PID" || fail "TERM-ignoring control-plane descendant survived KILL fallback"
wait_pid_gone "$FRONTEND_PID" || fail "frontend survived cleanup"

# A frontend startup failure must clean up the already-ready control plane.
cat > "$FIXTURE/frontend/node_modules/.bin/vite" <<'EOF'
#!/usr/bin/env bash
exit 7
EOF
chmod +x "$FIXTURE/frontend/node_modules/.bin/vite"
FAIL_PORT="$(free_port)"
if PI_SCIENCE_PYTHON="$(command -v python3)" PI_CLI_PATH="$FIXTURE/pi-cli.mjs" PI_SCIENCE_CONTROL_PLANE_PORT="$FAIL_PORT" PI_SCIENCE_RUNTIME_PORT="$(free_port)" PI_SCIENCE_FRONTEND_PORT="$(free_port)" PI_SCIENCE_STARTUP_TIMEOUT_SECONDS=3 bash "$FIXTURE/scripts/start.sh" >"$TEMP_ROOT/failure.log" 2>&1; then fail "frontend startup failure returned success"; fi
wait_port_available "$FAIL_PORT" || fail "startup failure left the control-plane port occupied"
assert_contains "$TEMP_ROOT/failure.log" 'frontend exited during startup'

# Missing package-local dependencies fail before starting either service.
cp "$FIXTURE/apps/server/node_modules/tsx/dist/cli.mjs" "$TEMP_ROOT/fake-tsx.mjs"
rm -f "$FIXTURE/apps/server/node_modules/tsx/dist/cli.mjs"
if PI_SCIENCE_PYTHON="$(command -v python3)" PI_CLI_PATH="$FIXTURE/pi-cli.mjs" bash "$FIXTURE/scripts/start.sh" >"$TEMP_ROOT/missing-tsx.log" 2>&1; then fail "missing tsx dependency returned success"; fi
assert_contains "$TEMP_ROOT/missing-tsx.log" 'server dependencies are not installed. Run: bash scripts/install.sh'
cp "$TEMP_ROOT/fake-tsx.mjs" "$FIXTURE/apps/server/node_modules/tsx/dist/cli.mjs"
rm -f "$FIXTURE/frontend/node_modules/.bin/vite"
if PI_SCIENCE_PYTHON="$(command -v python3)" PI_CLI_PATH="$FIXTURE/pi-cli.mjs" bash "$FIXTURE/scripts/start.sh" >"$TEMP_ROOT/missing-vite.log" 2>&1; then fail "missing Vite dependency returned success"; fi
assert_contains "$TEMP_ROOT/missing-vite.log" 'frontend dependencies are not installed. Run: bash scripts/install.sh'
cat > "$FIXTURE/frontend/node_modules/.bin/vite" <<EOF
#!/usr/bin/env bash
exec "$(command -v node)" "$FIXTURE/frontend/fake-vite.mjs" "\$@"
EOF
chmod +x "$FIXTURE/frontend/node_modules/.bin/vite"

# Invalid detached timeouts fail before the supervisor or services are spawned.
rm -f "$FIXTURE/control.pid" "$FIXTURE/.runtime/pi-science/run.state"
INVALID_CONTROL_PORT="$(free_port)"; INVALID_RUNTIME_PORT="$(free_port)"; INVALID_FRONTEND_PORT="$(free_port)"
if PI_SCIENCE_CONTROL_PLANE_PORT="$INVALID_CONTROL_PORT" PI_SCIENCE_RUNTIME_PORT="$INVALID_RUNTIME_PORT" PI_SCIENCE_FRONTEND_PORT="$INVALID_FRONTEND_PORT" PI_SCIENCE_STARTUP_TIMEOUT_SECONDS=invalid bash "$FIXTURE/scripts/pi-science.sh" start --detach --no-open >"$TEMP_ROOT/invalid-timeout.log" 2>&1; then fail "invalid detached timeout returned success"; fi
assert_contains "$TEMP_ROOT/invalid-timeout.log" 'must be a positive integer'
[ ! -e "$FIXTURE/control.pid" ] || fail "invalid timeout spawned the control plane"
[ ! -e "$FIXTURE/.runtime/pi-science/run.state" ] || fail "invalid timeout left run.state"

# Invalid PI_SCIENCE_SERVER_WATCH values fail before any service is spawned.
rm -f "$FIXTURE/control.pid" "$FIXTURE/.runtime/pi-science/run.state"
INVALID_WATCH_PORT="$(free_port)"
if PI_SCIENCE_PYTHON="$(command -v python3)" PI_CLI_PATH="$FIXTURE/pi-cli.mjs" PI_SCIENCE_SERVER_WATCH=yes PI_SCIENCE_CONTROL_PLANE_PORT="$INVALID_WATCH_PORT" PI_SCIENCE_RUNTIME_PORT="$(free_port)" PI_SCIENCE_FRONTEND_PORT="$(free_port)" bash "$FIXTURE/scripts/start.sh" >"$TEMP_ROOT/invalid-watch.log" 2>&1; then fail "invalid PI_SCIENCE_SERVER_WATCH returned success"; fi
assert_contains "$TEMP_ROOT/invalid-watch.log" 'PI_SCIENCE_SERVER_WATCH must be 0 or 1'
[ ! -e "$FIXTURE/control.pid" ] || fail "invalid watch value spawned the control plane"
wait_port_available "$INVALID_WATCH_PORT" || fail "invalid watch value left the control-plane port occupied"

# A live checkout-local launch lock refuses a simultaneous detached contender
# before it can commit supervisor state.
CONCURRENT_BARRIER="$TEMP_ROOT/concurrent-bootstrap"
CONCURRENT_CONTROL_PORT="$(free_port)"; CONCURRENT_RUNTIME_PORT="$(free_port)"; CONCURRENT_FRONTEND_PORT="$(free_port)"
rm -f "$CONCURRENT_BARRIER.ready" "$CONCURRENT_BARRIER.release"
PI_SCIENCE_PYTHON="$(command -v python3)" PI_CLI_PATH="$FIXTURE/pi-cli.mjs" PI_SCIENCE_CONTROL_PLANE_PORT="$CONCURRENT_CONTROL_PORT" PI_SCIENCE_RUNTIME_PORT="$CONCURRENT_RUNTIME_PORT" PI_SCIENCE_FRONTEND_PORT="$CONCURRENT_FRONTEND_PORT" PI_SCIENCE_STARTUP_TIMEOUT_SECONDS=8 PI_SCIENCE_TEST_BOOTSTRAP_BARRIER="$CONCURRENT_BARRIER" bash "$FIXTURE/scripts/pi-science.sh" start --detach --no-open >"$TEMP_ROOT/concurrent-owner.log" 2>&1 &
CONCURRENT_OWNER_PID=$!
wait_file "$CONCURRENT_BARRIER.ready" || fail "concurrent launch owner did not reach bootstrap barrier"
if PI_SCIENCE_CONTROL_PLANE_PORT="$CONCURRENT_CONTROL_PORT" PI_SCIENCE_RUNTIME_PORT="$CONCURRENT_RUNTIME_PORT" PI_SCIENCE_FRONTEND_PORT="$CONCURRENT_FRONTEND_PORT" bash "$FIXTURE/scripts/pi-science.sh" start --detach --no-open >"$TEMP_ROOT/concurrent-contender.log" 2>&1; then fail "concurrent detached contender returned success"; fi
assert_contains "$TEMP_ROOT/concurrent-contender.log" 'another Pi-Science detached launch transaction is active'
: > "$CONCURRENT_BARRIER.release"
wait "$CONCURRENT_OWNER_PID" || { cat "$TEMP_ROOT/concurrent-owner.log" >&2; fail "concurrent launch owner failed"; }
[ -d "$FIXTURE/.runtime/pi-science/run.state" ] || fail "concurrent owner did not commit run.state"
CONCURRENT_STATE_PID="$(cat "$FIXTURE/.runtime/pi-science/run.state/pid")"
PI_SCIENCE_CONTROL_PLANE_PORT="$CONCURRENT_CONTROL_PORT" PI_SCIENCE_RUNTIME_PORT="$CONCURRENT_RUNTIME_PORT" PI_SCIENCE_FRONTEND_PORT="$CONCURRENT_FRONTEND_PORT" bash "$FIXTURE/scripts/pi-science.sh" stop >/dev/null
wait_pid_gone "$CONCURRENT_STATE_PID" || fail "concurrent owner supervisor survived stop"
[ ! -e "$FIXTURE/.runtime/pi-science/start.lock" ] || fail "concurrent launch lock leaked"

# TERM between supervisor spawn and state commit rolls back only that bootstrap
# transaction and leaves no untracked supervisor, state or lock.
SIGNAL_BOOTSTRAP_BARRIER="$TEMP_ROOT/signal-bootstrap"
SIGNAL_CONTROL_PORT="$(free_port)"; SIGNAL_RUNTIME_PORT="$(free_port)"; SIGNAL_FRONTEND_PORT="$(free_port)"
rm -f "$SIGNAL_BOOTSTRAP_BARRIER.ready" "$SIGNAL_BOOTSTRAP_BARRIER.release"
PI_SCIENCE_PYTHON="$(command -v python3)" PI_CLI_PATH="$FIXTURE/pi-cli.mjs" PI_SCIENCE_CONTROL_PLANE_PORT="$SIGNAL_CONTROL_PORT" PI_SCIENCE_RUNTIME_PORT="$SIGNAL_RUNTIME_PORT" PI_SCIENCE_FRONTEND_PORT="$SIGNAL_FRONTEND_PORT" PI_SCIENCE_STARTUP_TIMEOUT_SECONDS=8 PI_SCIENCE_TEST_BOOTSTRAP_BARRIER="$SIGNAL_BOOTSTRAP_BARRIER" bash "$FIXTURE/scripts/pi-science.sh" start --detach --no-open >"$TEMP_ROOT/signal-bootstrap.log" 2>&1 &
SIGNAL_BOOTSTRAP_PID=$!
wait_file "$SIGNAL_BOOTSTRAP_BARRIER.ready" || fail "signalled bootstrap did not reach barrier"
SIGNAL_SUPERVISOR_PID="$(cat "$SIGNAL_BOOTSTRAP_BARRIER.pid")"
kill -TERM "$SIGNAL_BOOTSTRAP_PID"
set +e
wait "$SIGNAL_BOOTSTRAP_PID"; SIGNAL_BOOTSTRAP_STATUS=$?
set -e
[ "$SIGNAL_BOOTSTRAP_STATUS" -eq 143 ] || fail "signalled bootstrap exited $SIGNAL_BOOTSTRAP_STATUS instead of 143"
[ ! -e "$FIXTURE/.runtime/pi-science/run.state" ] || fail "signalled bootstrap left run.state"
[ ! -e "$FIXTURE/.runtime/pi-science/start.lock" ] || fail "signalled bootstrap left its transaction lock"
wait_pid_gone "$SIGNAL_SUPERVISOR_PID" || fail "signalled bootstrap left the published supervisor alive"
wait_port_available "$SIGNAL_CONTROL_PORT" || fail "signalled bootstrap left control-plane port occupied"
wait_port_available "$SIGNAL_FRONTEND_PORT" || fail "signalled bootstrap left frontend port occupied"

# A dead launch-lock owner is reclaimed, while a live owner is never displaced.
DEAD_LOCK="$FIXTURE/.runtime/pi-science/start.lock"
mkdir -p "$DEAD_LOCK"
printf 'pid=999999\nstarted=dead-owner\ntoken=dead-token\n' > "$DEAD_LOCK/owner"
if PI_SCIENCE_STARTUP_TIMEOUT_SECONDS=invalid bash "$FIXTURE/scripts/pi-science.sh" start --detach --no-open >"$TEMP_ROOT/dead-lock.log" 2>&1; then fail "dead-lock preflight returned success"; fi
assert_not_contains "$TEMP_ROOT/dead-lock.log" 'another Pi-Science detached launch transaction is active'
[ ! -e "$DEAD_LOCK" ] || fail "dead launch lock was not reclaimed and released"
LIVE_LOCK_STARTED="$(PI_SCIENCE_SOURCE_ONLY=1 bash -c 'source "$1"; process_start_identity "$2"' _ "$FIXTURE/scripts/pi-science.sh" "$$")"
mkdir -p "$DEAD_LOCK"
printf 'pid=%s\nstarted=%s\ntoken=live-token\n' "$$" "$LIVE_LOCK_STARTED" > "$DEAD_LOCK/owner"
if bash "$FIXTURE/scripts/pi-science.sh" start --detach --no-open >"$TEMP_ROOT/live-lock.log" 2>&1; then fail "live launch lock was displaced"; fi
assert_contains "$TEMP_ROOT/live-lock.log" 'another Pi-Science detached launch transaction is active'
[ -e "$DEAD_LOCK" ] || fail "live owner lock was removed"
rm -rf "$DEAD_LOCK"

# A live owner whose process identity is inaccessible is unverifiable, not dead,
# and its lock is never reclaimed.
LOCK_IDENTITY_DIR="$TEMP_ROOT/lock-identities"
mkdir -p "$LOCK_IDENTITY_DIR" "$DEAD_LOCK"
: > "$LOCK_IDENTITY_DIR/$$"
printf 'pid=%s\nstarted=recorded-but-inaccessible\ntoken=unverifiable-token\n' "$$" > "$DEAD_LOCK/owner"
if PI_SCIENCE_TEST_PROCESS_IDENTITY_DIR="$LOCK_IDENTITY_DIR" bash "$FIXTURE/scripts/pi-science.sh" start --detach --no-open >"$TEMP_ROOT/unverifiable-lock.log" 2>&1; then fail "unverifiable live launch lock was displaced"; fi
assert_contains "$TEMP_ROOT/unverifiable-lock.log" 'stale launch lock has unverifiable ownership'
[ -e "$DEAD_LOCK" ] || fail "unverifiable live owner lock was removed"
rm -rf "$DEAD_LOCK"

# Stale-lock reclamation is generation-bound to the inspected owner inode. A
# delayed reclaimer A must not quarantine the live lock installed by winner B.
# Killing B immediately after arbitration still leaves recoverable ownership.
PRE_QUARANTINE_BARRIER="$TEMP_ROOT/pre-quarantine"
RECLAIM_BARRIER="$TEMP_ROOT/stale-reclaim"
rm -f "$PRE_QUARANTINE_BARRIER.ready" "$PRE_QUARANTINE_BARRIER.release" "$RECLAIM_BARRIER.ready" "$RECLAIM_BARRIER.release" "$RECLAIM_BARRIER.winner"
mkdir -p "$DEAD_LOCK"
printf 'pid=999999\nstarted=dead-owner\ntoken=dead-token\n' > "$DEAD_LOCK/owner"
PI_SCIENCE_STARTUP_TIMEOUT_SECONDS=invalid PI_SCIENCE_TEST_PRE_QUARANTINE_BARRIER="$PRE_QUARANTINE_BARRIER" bash "$FIXTURE/scripts/pi-science.sh" start --detach --no-open >"$TEMP_ROOT/reclaim-delayed-a.log" 2>&1 &
RECLAIM_DELAYED_A_PID=$!
wait_file "$PRE_QUARANTINE_BARRIER.ready" || fail "delayed stale-lock reclaimer did not reach pre-quarantine barrier"
PI_SCIENCE_STARTUP_TIMEOUT_SECONDS=invalid PI_SCIENCE_TEST_RECLAIM_BARRIER="$RECLAIM_BARRIER" bash "$FIXTURE/scripts/pi-science.sh" start --detach --no-open >"$TEMP_ROOT/reclaim-winner-b.log" 2>&1 &
RECLAIM_WINNER_PID=$!
wait_file "$RECLAIM_BARRIER.ready" || fail "stale-lock arbitration winner did not reach barrier"
[ "$(cat "$RECLAIM_BARRIER.winner")" = "$RECLAIM_WINNER_PID" ] || fail "stale-lock winner PID was not published"
: > "$PRE_QUARANTINE_BARRIER.release"
set +e
wait "$RECLAIM_DELAYED_A_PID"; RECLAIM_DELAYED_A_STATUS=$?
set -e
[ "$RECLAIM_DELAYED_A_STATUS" -ne 0 ] || fail "delayed reclaimer displaced the newer winner"
kill -0 "$RECLAIM_WINNER_PID" 2>/dev/null || fail "winner B died when delayed reclaimer A resumed"
assert_contains "$DEAD_LOCK/owner" "pid=$RECLAIM_WINNER_PID"
assert_contains "$TEMP_ROOT/reclaim-delayed-a.log" 'replaced the stale lock before recovery'
kill -KILL "$RECLAIM_WINNER_PID"; wait "$RECLAIM_WINNER_PID" 2>/dev/null || true
if PI_SCIENCE_STARTUP_TIMEOUT_SECONDS=invalid bash "$FIXTURE/scripts/pi-science.sh" start --detach --no-open >"$TEMP_ROOT/reclaim-recovery.log" 2>&1; then fail "invalid-timeout recovery unexpectedly succeeded"; fi
assert_not_contains "$TEMP_ROOT/reclaim-recovery.log" 'another Pi-Science detached launch transaction is active'
assert_not_contains "$TEMP_ROOT/reclaim-recovery.log" 'stale launch lock has unverifiable ownership'
[ ! -e "$DEAD_LOCK" ] || fail "recovered launch lock remained"
if find "$FIXTURE/.runtime/pi-science" -maxdepth 1 \( -name 'start.lock.reclaim' -o -name '.start.lock.stale.*' -o -name '.start.lock.claim.*' -o -name '.start.lock.*' \) -print | grep -q .; then fail "stale-lock arbitration artifact remained"; fi

# SIGKILL after supervisor spawn leaves a verifiably stale lock, not a permanent
# start blockage. The next launch reclaims the lock and reports the surviving
# unverified listener; manual cleanup uses the published fenced supervisor ID.
KILL_BOOTSTRAP_BARRIER="$TEMP_ROOT/kill-bootstrap"
KILL_CONTROL_PORT="$(free_port)"; KILL_RUNTIME_PORT="$(free_port)"; KILL_FRONTEND_PORT="$(free_port)"
rm -f "$KILL_BOOTSTRAP_BARRIER.ready" "$KILL_BOOTSTRAP_BARRIER.release" "$KILL_BOOTSTRAP_BARRIER.pid" "$KILL_BOOTSTRAP_BARRIER.started"
PI_SCIENCE_PYTHON="$(command -v python3)" PI_CLI_PATH="$FIXTURE/pi-cli.mjs" PI_SCIENCE_CONTROL_PLANE_PORT="$KILL_CONTROL_PORT" PI_SCIENCE_RUNTIME_PORT="$KILL_RUNTIME_PORT" PI_SCIENCE_FRONTEND_PORT="$KILL_FRONTEND_PORT" PI_SCIENCE_STARTUP_TIMEOUT_SECONDS=8 PI_SCIENCE_TEST_BOOTSTRAP_BARRIER="$KILL_BOOTSTRAP_BARRIER" bash "$FIXTURE/scripts/pi-science.sh" start --detach --no-open >"$TEMP_ROOT/kill-bootstrap-owner.log" 2>&1 &
KILL_BOOTSTRAP_OWNER=$!
wait_file "$KILL_BOOTSTRAP_BARRIER.ready" || fail "SIGKILL bootstrap did not reach barrier"
KILL_SUPERVISOR_PID="$(cat "$KILL_BOOTSTRAP_BARRIER.pid")"; KILL_SUPERVISOR_STARTED="$(cat "$KILL_BOOTSTRAP_BARRIER.started")"
kill -KILL "$KILL_BOOTSTRAP_OWNER"; wait "$KILL_BOOTSTRAP_OWNER" 2>/dev/null || true
wait_url "http://127.0.0.1:$KILL_CONTROL_PORT/api/health" || fail "SIGKILL residual supervisor did not become observable"
if PI_SCIENCE_CONTROL_PLANE_PORT="$KILL_CONTROL_PORT" PI_SCIENCE_RUNTIME_PORT="$KILL_RUNTIME_PORT" PI_SCIENCE_FRONTEND_PORT="$KILL_FRONTEND_PORT" bash "$FIXTURE/scripts/pi-science.sh" start --detach --no-open >"$TEMP_ROOT/kill-bootstrap-recovery.log" 2>&1; then fail "residual supervisor was silently reused"; fi
assert_not_contains "$TEMP_ROOT/kill-bootstrap-recovery.log" 'another Pi-Science detached launch transaction is active'
assert_contains "$TEMP_ROOT/kill-bootstrap-recovery.log" 'already in use by an unverified process'
[ ! -e "$FIXTURE/.runtime/pi-science/start.lock" ] || fail "recovered stale launch lock remained"
PI_SCIENCE_SOURCE_ONLY=1 bash -c 'source "$1"; stop_process_tree "$2" "$3"' _ "$FIXTURE/scripts/pi-science.sh" "$KILL_SUPERVISOR_PID" "$KILL_SUPERVISOR_STARTED"
wait_pid_gone "$KILL_SUPERVISOR_PID" || fail "documented residual supervisor cleanup failed"
wait_port_available "$KILL_CONTROL_PORT" || fail "documented residual cleanup left control port occupied"

# A stale state file pointing at an unrelated live PID is discarded without
# signaling that process, even if its start timestamp is valid.
sleep 30 &
UNRELATED_PID=$!
mkdir -p "$FIXTURE/.runtime/pi-science/run.state"
printf '%s\n' "$UNRELATED_PID" > "$FIXTURE/.runtime/pi-science/run.state/pid"
printf '%s\n' 'not-the-launch-token' > "$FIXTURE/.runtime/pi-science/run.state/token"
ps -ww -o lstart= -p "$UNRELATED_PID" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' > "$FIXTURE/.runtime/pi-science/run.state/started"
printf '%s\n' "$FIXTURE" > "$FIXTURE/.runtime/pi-science/run.state/checkout"
bash "$FIXTURE/scripts/pi-science.sh" status >"$TEMP_ROOT/unrelated-status.log"
kill -0 "$UNRELATED_PID" 2>/dev/null || fail "status killed an unrelated live PID"
[ ! -e "$FIXTURE/.runtime/pi-science/run.state" ] || fail "mismatched supervisor state was not removed"
bash "$FIXTURE/scripts/pi-science.sh" stop >/dev/null
kill -0 "$UNRELATED_PID" 2>/dev/null || fail "stop killed an unrelated live PID"
kill "$UNRELATED_PID"; wait "$UNRELATED_PID" 2>/dev/null || true

# A pre-existing checkout-local health listener is refused and survives rollback.
PREEXISTING_PORT="$(free_port)"
node -e 'require("node:http").createServer((_q,r)=>{r.writeHead(200);r.end("existing")}).listen(Number(process.argv[1]),"127.0.0.1");' "$PREEXISTING_PORT" &
PREEXISTING_PID=$!
wait_url "http://127.0.0.1:$PREEXISTING_PORT/api/health" || fail "pre-existing listener did not start"
if PI_SCIENCE_CONTROL_PLANE_PORT="$PREEXISTING_PORT" PI_SCIENCE_RUNTIME_PORT="$(free_port)" PI_SCIENCE_FRONTEND_PORT="$(free_port)" bash "$FIXTURE/scripts/pi-science.sh" start --detach --no-open >"$TEMP_ROOT/pre-existing.log" 2>&1; then fail "pre-existing listener was reused"; fi
assert_contains "$TEMP_ROOT/pre-existing.log" 'already in use by an unverified process'
kill -0 "$PREEXISTING_PID" 2>/dev/null || fail "startup refusal killed a pre-existing listener"
kill "$PREEXISTING_PID"; wait "$PREEXISTING_PID" 2>/dev/null || true

# Sequential slow readiness remains within one coherent detached deadline.
DETACH_CONTROL_PORT="$(free_port)"; DETACH_RUNTIME_PORT="$(free_port)"; DETACH_FRONTEND_PORT="$(free_port)"
PI_SCIENCE_PYTHON="$(command -v python3)" PI_CLI_PATH="$FIXTURE/pi-cli.mjs" PI_SCIENCE_CONTROL_PLANE_PORT="$DETACH_CONTROL_PORT" PI_SCIENCE_RUNTIME_PORT="$DETACH_RUNTIME_PORT" PI_SCIENCE_FRONTEND_PORT="$DETACH_FRONTEND_PORT" PI_SCIENCE_STARTUP_TIMEOUT_SECONDS=5 PI_SCIENCE_TEST_CONTROL_DELAY_MS=1200 PI_SCIENCE_TEST_FRONTEND_DELAY_MS=1200 bash "$FIXTURE/scripts/pi-science.sh" start --detach --no-open >"$TEMP_ROOT/detach.log"
assert_contains "$TEMP_ROOT/detach.log" 'running in the background'
[ -d "$FIXTURE/.runtime/pi-science/run.state" ] || fail "detached start did not write run.state"
PI_SCIENCE_CONTROL_PLANE_PORT="$DETACH_CONTROL_PORT" PI_SCIENCE_RUNTIME_PORT="$DETACH_RUNTIME_PORT" PI_SCIENCE_FRONTEND_PORT="$DETACH_FRONTEND_PORT" bash "$FIXTURE/scripts/pi-science.sh" status >"$TEMP_ROOT/status.log"
assert_contains "$TEMP_ROOT/status.log" 'Supervisor:         running'
assert_contains "$TEMP_ROOT/status.log" 'Node control plane: ready'
DETACH_SUPERVISOR_PID="$(cat "$FIXTURE/.runtime/pi-science/run.state/pid")"
DETACH_CONTROL_PID="$(cat "$FIXTURE/control.pid")"
DETACH_CONTROL_CHILD_PID="$(cat "$FIXTURE/control.child.pid")"
DETACH_FRONTEND_PID="$(cat "$FIXTURE/frontend.pid")"
PI_SCIENCE_CONTROL_PLANE_PORT="$DETACH_CONTROL_PORT" PI_SCIENCE_RUNTIME_PORT="$DETACH_RUNTIME_PORT" PI_SCIENCE_FRONTEND_PORT="$DETACH_FRONTEND_PORT" bash "$FIXTURE/scripts/pi-science.sh" stop >"$TEMP_ROOT/stop.log"
[ ! -e "$FIXTURE/.runtime/pi-science/run.state" ] || fail "stop left run.state"
wait_port_available "$DETACH_CONTROL_PORT" || fail "detached stop left control-plane port occupied"
wait_port_available "$DETACH_FRONTEND_PORT" || fail "detached stop left frontend port occupied"
wait_pid_gone "$DETACH_SUPERVISOR_PID" || fail "detached stop left supervisor alive"
wait_pid_gone "$DETACH_CONTROL_PID" || fail "detached stop left control plane alive"
wait_pid_gone "$DETACH_CONTROL_CHILD_PID" || fail "detached stop left TERM-ignoring descendant alive"
wait_pid_gone "$DETACH_FRONTEND_PID" || fail "detached stop left frontend alive"

# A never-ready detached frontend rolls back its supervisor, PID file and ports.
NEVER_CONTROL_PORT="$(free_port)"; NEVER_RUNTIME_PORT="$(free_port)"; NEVER_FRONTEND_PORT="$(free_port)"
if PI_SCIENCE_PYTHON="$(command -v python3)" PI_CLI_PATH="$FIXTURE/pi-cli.mjs" PI_SCIENCE_CONTROL_PLANE_PORT="$NEVER_CONTROL_PORT" PI_SCIENCE_RUNTIME_PORT="$NEVER_RUNTIME_PORT" PI_SCIENCE_FRONTEND_PORT="$NEVER_FRONTEND_PORT" PI_SCIENCE_STARTUP_TIMEOUT_SECONDS=2 PI_SCIENCE_TEST_FRONTEND_NEVER_READY=1 bash "$FIXTURE/scripts/pi-science.sh" start --detach --no-open >"$TEMP_ROOT/never.log" 2>&1; then fail "never-ready detached start returned success"; fi
assert_contains "$TEMP_ROOT/never.log" 'did not become ready within 2s'
[ ! -e "$FIXTURE/.runtime/pi-science/run.state" ] || fail "timed-out detached start left run.state"
NEVER_CONTROL_PID="$(cat "$FIXTURE/control.pid")"; NEVER_CONTROL_CHILD_PID="$(cat "$FIXTURE/control.child.pid")"; NEVER_FRONTEND_PID="$(cat "$FIXTURE/frontend.pid")"
wait_port_available "$NEVER_CONTROL_PORT" || fail "timed-out detached start left control-plane port occupied"
wait_port_available "$NEVER_FRONTEND_PORT" || fail "timed-out detached start left frontend port occupied"
wait_pid_gone "$NEVER_CONTROL_PID" || fail "deadline rollback left control plane alive"
wait_pid_gone "$NEVER_CONTROL_CHILD_PID" || fail "deadline rollback left TERM-ignoring descendant alive"
wait_pid_gone "$NEVER_FRONTEND_PID" || fail "deadline rollback left frontend alive"

# The watch opt-in passes the watch argument to tsx and logs the mode; default
# stays direct so detached supervisors never see a tsx watch restart loop.
WATCH_CONTROL_PORT="$(free_port)"; WATCH_RUNTIME_PORT="$(free_port)"; WATCH_FRONTEND_PORT="$(free_port)"
rm -f "$FIXTURE/control.pid"
PI_SCIENCE_PYTHON="$(command -v python3)" PI_CLI_PATH="$FIXTURE/pi-cli.mjs" PI_SCIENCE_SERVER_WATCH=1 PI_SCIENCE_CONTROL_PLANE_PORT="$WATCH_CONTROL_PORT" PI_SCIENCE_RUNTIME_PORT="$WATCH_RUNTIME_PORT" PI_SCIENCE_FRONTEND_PORT="$WATCH_FRONTEND_PORT" PI_SCIENCE_STARTUP_TIMEOUT_SECONDS=10 bash "$FIXTURE/scripts/start.sh" >"$TEMP_ROOT/watch.log" 2>&1 &
WATCH_START_PID=$!
wait_url "http://127.0.0.1:$WATCH_CONTROL_PORT/internal/ready" || { cat "$TEMP_ROOT/watch.log" >&2; fail "watch control plane did not become ready"; }
wait_url "http://127.0.0.1:$WATCH_FRONTEND_PORT" || { cat "$TEMP_ROOT/watch.log" >&2; fail "watch frontend did not become ready"; }
[ "$(cat "$FIXTURE/control.argv")" = '["watch","src/app/main.ts"]' ] || fail "watch opt-in argv is not watch mode: $(cat "$FIXTURE/control.argv")"
assert_contains "$TEMP_ROOT/watch.log" 'control plane mode: watch'
WATCH_CONTROL_PID="$(cat "$FIXTURE/control.pid")"; WATCH_FRONTEND_PID="$(cat "$FIXTURE/frontend.pid")"
kill -TERM "$WATCH_START_PID"
wait "$WATCH_START_PID" 2>/dev/null || true
WATCH_START_PID=""
wait_port_available "$WATCH_CONTROL_PORT" || fail "watch control-plane port was not released"
wait_port_available "$WATCH_FRONTEND_PORT" || fail "watch frontend port was not released"
wait_pid_gone "$WATCH_CONTROL_PID" || fail "watch control plane survived cleanup"
wait_pid_gone "$WATCH_FRONTEND_PID" || fail "watch frontend survived cleanup"

# SIGINT delivery from a foreground parent models terminal Ctrl+C without the
# signal-ignore semantics Bash applies to its own asynchronous children.
INT_CONTROL_PORT="$(free_port)"; INT_RUNTIME_PORT="$(free_port)"; INT_FRONTEND_PORT="$(free_port)"
cat > "$TEMP_ROOT/test-sigint.py" <<'PY'
import os, signal, socket, subprocess, sys, time, urllib.request
script, control, runtime, frontend, python, cli, log = sys.argv[1:]
env = {**os.environ, "PI_SCIENCE_PYTHON": python, "PI_CLI_PATH": cli, "PI_SCIENCE_CONTROL_PLANE_PORT": control, "PI_SCIENCE_RUNTIME_PORT": runtime, "PI_SCIENCE_FRONTEND_PORT": frontend, "PI_SCIENCE_STARTUP_TIMEOUT_SECONDS": "5"}
with open(log, "wb") as output:
    child = subprocess.Popen(["bash", script], env=env, stdout=output, stderr=subprocess.STDOUT)
    deadline = time.time() + 10
    for url in (f"http://127.0.0.1:{control}/internal/ready", f"http://127.0.0.1:{frontend}"):
        while True:
            try:
                urllib.request.urlopen(url, timeout=.2).read(); break
            except Exception:
                if child.poll() is not None or time.time() >= deadline: raise
                time.sleep(.05)
    child.send_signal(signal.SIGINT)
    code = child.wait(timeout=15)
    if code != 130: raise SystemExit(f"expected SIGINT exit 130, got {code}")
for port in (control, frontend):
    with socket.socket() as sock:
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        sock.bind(("127.0.0.1", int(port)))
PY
python3 "$TEMP_ROOT/test-sigint.py" "$FIXTURE/scripts/start.sh" "$INT_CONTROL_PORT" "$INT_RUNTIME_PORT" "$INT_FRONTEND_PORT" "$(command -v python3)" "$FIXTURE/pi-cli.mjs" "$TEMP_ROOT/int.log" || { cat "$TEMP_ROOT/int.log" >&2; fail "SIGINT cleanup failed"; }

# Descendant cleanup fences every snapshot PID with its process-start identity.
# Injecting a changed identity after the snapshot proves a reused PID is skipped.
IDENTITY_DIR="$TEMP_ROOT/process-identities"; IDENTITY_BARRIER="$TEMP_ROOT/process-snapshot"
mkdir -p "$IDENTITY_DIR"; rm -f "$IDENTITY_BARRIER.ready" "$IDENTITY_BARRIER.release"
bash -c 'sleep 30 & echo $! > "$1"; wait' _ "$TEMP_ROOT/reused-child.pid" &
REUSED_ROOT_PID=$!
wait_file "$TEMP_ROOT/reused-child.pid" || fail "PID-reuse fixture child did not start"
REUSED_CHILD_PID="$(cat "$TEMP_ROOT/reused-child.pid")"
REUSED_ROOT_STARTED="$(PI_SCIENCE_SOURCE_ONLY=1 PI_SCIENCE_TEST_PROCESS_IDENTITY_DIR="$IDENTITY_DIR" bash -c 'source "$1"; process_start_identity "$2"' _ "$FIXTURE/scripts/pi-science.sh" "$REUSED_ROOT_PID")"
PI_SCIENCE_SOURCE_ONLY=1 PI_SCIENCE_TEST_PROCESS_IDENTITY_DIR="$IDENTITY_DIR" PI_SCIENCE_TEST_PROCESS_SNAPSHOT_BARRIER="$IDENTITY_BARRIER" bash -c 'source "$1"; stop_process_tree "$2" "$3"' _ "$FIXTURE/scripts/pi-science.sh" "$REUSED_ROOT_PID" "$REUSED_ROOT_STARTED" &
REUSED_STOPPER_PID=$!
wait_file "$IDENTITY_BARRIER.ready" || fail "process snapshot barrier was not reached"
printf 'reused-process-start-identity\n' > "$IDENTITY_DIR/$REUSED_CHILD_PID"
: > "$IDENTITY_BARRIER.release"
wait "$REUSED_STOPPER_PID" || fail "identity-fenced stop helper failed"
kill -0 "$REUSED_CHILD_PID" 2>/dev/null || fail "changed-identity descendant was signalled"
kill "$REUSED_CHILD_PID" 2>/dev/null || true
wait "$REUSED_ROOT_PID" 2>/dev/null || true

# A changed root identity prevents both a new traversal and every TERM/KILL.
ROOT_IDENTITY_BARRIER="$TEMP_ROOT/root-process-snapshot"
rm -f "$ROOT_IDENTITY_BARRIER.ready" "$ROOT_IDENTITY_BARRIER.release" "$TEMP_ROOT/reused-root-child.pid"
bash -c 'sleep 30 & echo $! > "$1"; wait' _ "$TEMP_ROOT/reused-root-child.pid" &
CHANGED_ROOT_PID=$!
wait_file "$TEMP_ROOT/reused-root-child.pid" || fail "changed-root fixture child did not start"
CHANGED_ROOT_CHILD_PID="$(cat "$TEMP_ROOT/reused-root-child.pid")"
CHANGED_ROOT_STARTED="$(PI_SCIENCE_SOURCE_ONLY=1 PI_SCIENCE_TEST_PROCESS_IDENTITY_DIR="$IDENTITY_DIR" bash -c 'source "$1"; process_start_identity "$2"' _ "$FIXTURE/scripts/pi-science.sh" "$CHANGED_ROOT_PID")"
PI_SCIENCE_SOURCE_ONLY=1 PI_SCIENCE_TEST_PROCESS_IDENTITY_DIR="$IDENTITY_DIR" PI_SCIENCE_TEST_PROCESS_SNAPSHOT_BARRIER="$ROOT_IDENTITY_BARRIER" bash -c 'source "$1"; stop_process_tree "$2" "$3"' _ "$FIXTURE/scripts/pi-science.sh" "$CHANGED_ROOT_PID" "$CHANGED_ROOT_STARTED" &
CHANGED_ROOT_STOPPER=$!
wait_file "$ROOT_IDENTITY_BARRIER.ready" || fail "changed-root snapshot barrier was not reached"
printf 'reused-root-start-identity\n' > "$IDENTITY_DIR/$CHANGED_ROOT_PID"
: > "$ROOT_IDENTITY_BARRIER.release"
wait "$CHANGED_ROOT_STOPPER" || fail "changed-root stop helper failed"
kill -0 "$CHANGED_ROOT_PID" 2>/dev/null || fail "changed-identity root was signalled"
kill -0 "$CHANGED_ROOT_CHILD_PID" 2>/dev/null || fail "child was signalled after root identity changed"
kill "$CHANGED_ROOT_CHILD_PID" "$CHANGED_ROOT_PID" 2>/dev/null || true
wait "$CHANGED_ROOT_PID" 2>/dev/null || true

echo "launcher contract and lifecycle tests passed"
