#!/usr/bin/env bash
# Atomically install the PATH launcher for one Pi-Science checkout.
set -euo pipefail

[ "$#" -eq 2 ] || { echo "Usage: write-launcher.sh PROJECT_DIR BIN_DIR" >&2; exit 2; }
PROJECT_DIR="$1"
BIN_DIR="$2"
LAUNCHER="$BIN_DIR/pi-science"
LAUNCHER_MARKER='# pi-science-launcher-v1'
PROJECT_ASSIGNMENT="$(printf 'PI_SCIENCE_DIR=%q' "$PROJECT_DIR")"
mkdir -p "$BIN_DIR"

launcher_is_owned() {
  [ -f "$LAUNCHER" ] && [ ! -L "$LAUNCHER" ] || return 1
  grep -Fqx "$PROJECT_ASSIGNMENT" "$LAUNCHER" || return 1
  grep -Fqx "$LAUNCHER_MARKER" "$LAUNCHER" || grep -Fqx '# Generated by scripts/install.sh. Re-run it if this checkout moves.' "$LAUNCHER"
}

if [ -L "$LAUNCHER" ] || [ -d "$LAUNCHER" ] || { [ -e "$LAUNCHER" ] && ! launcher_is_owned; }; then
  echo "Error: refusing to overwrite unrelated launcher path: $LAUNCHER" >&2
  echo "Move or remove it explicitly, then rerun: bash scripts/install.sh" >&2
  exit 1
fi

LAUNCHER_TEMP="$(mktemp "$BIN_DIR/.pi-science-launcher.XXXXXX")"
cleanup_launcher_temp() { rm -f "$LAUNCHER_TEMP"; }
trap cleanup_launcher_temp EXIT
{
  echo '#!/usr/bin/env bash'
  echo "$LAUNCHER_MARKER"
  echo '# Generated by scripts/install.sh. Re-run it if this checkout moves.'
  printf '%s\n' "$PROJECT_ASSIGNMENT"
  echo '[ -f "$PI_SCIENCE_DIR/scripts/pi-science.sh" ] || { echo "Error: the Pi-Science checkout at $PI_SCIENCE_DIR is gone. Re-run scripts/install.sh from its new location." >&2; exit 1; }'
  echo 'exec bash "$PI_SCIENCE_DIR/scripts/pi-science.sh" "$@"'
} > "$LAUNCHER_TEMP"
chmod +x "$LAUNCHER_TEMP"
mv -f "$LAUNCHER_TEMP" "$LAUNCHER"
trap - EXIT
