#!/usr/bin/env bash
# Install the PATH launcher for one Pi-Science checkout without clobbering
# unrelated destinations. The lock coordinates Pi-Science installers; the
# hard-link commit refuses a destination created after validation.
set -euo pipefail

[ "$#" -eq 2 ] || { echo "Usage: write-launcher.sh PROJECT_DIR BIN_DIR" >&2; exit 2; }
PROJECT_DIR="$1"
BIN_DIR="$2"
LAUNCHER="$BIN_DIR/pi-science"
LAUNCHER_MARKER='# pi-science-launcher-v1'
PROJECT_ASSIGNMENT="$(printf 'PI_SCIENCE_DIR=%q' "$PROJECT_DIR")"
LOCK_DIR="$BIN_DIR/.pi-science-launcher.lock"
LAUNCHER_TEMP=""
OLD_SNAPSHOT=""
LOCK_OWNED=false
LOCK_TOKEN="$$-${RANDOM:-0}-$(date +%s)"
CLEANED=false
mkdir -p "$BIN_DIR"

cleanup() {
  [ "$CLEANED" = false ] || return 0
  CLEANED=true
  [ -z "$LAUNCHER_TEMP" ] || rm -f "$LAUNCHER_TEMP"
  [ -z "$OLD_SNAPSHOT" ] || rm -f "$OLD_SNAPSHOT"
  if [ "$LOCK_OWNED" = true ] && [ "$(cat "$LOCK_DIR/owner" 2>/dev/null || true)" = "$LOCK_TOKEN" ]; then rm -rf "$LOCK_DIR"; fi
}
on_int() { trap - INT TERM; cleanup; exit 130; }
on_term() { trap - INT TERM; cleanup; exit 143; }
trap cleanup EXIT
trap on_int INT
trap on_term TERM
mkdir "$LOCK_DIR" 2>/dev/null || { echo "Error: another Pi-Science launcher installation is active in $BIN_DIR" >&2; exit 1; }
LOCK_OWNED=true
printf '%s\n' "$LOCK_TOKEN" > "$LOCK_DIR/owner"

launcher_is_owned() {
  [ -f "$LAUNCHER" ] && [ ! -L "$LAUNCHER" ] || return 1
  grep -Fqx "$PROJECT_ASSIGNMENT" "$LAUNCHER" || return 1
  grep -Fqx "$LAUNCHER_MARKER" "$LAUNCHER" || grep -Fqx '# Generated by scripts/install.sh. Re-run it if this checkout moves.' "$LAUNCHER"
}

refuse_collision() {
  echo "Error: refusing to overwrite unrelated launcher path: $LAUNCHER" >&2
  echo "Move or remove it explicitly, then rerun: bash scripts/install.sh" >&2
  exit 1
}

if [ -e "$LAUNCHER" ] || [ -L "$LAUNCHER" ]; then launcher_is_owned || refuse_collision; fi

LAUNCHER_TEMP="$(mktemp "$BIN_DIR/.pi-science-launcher.XXXXXX")"
{
  echo '#!/usr/bin/env bash'
  echo "$LAUNCHER_MARKER"
  echo '# Generated by scripts/install.sh. Re-run it if this checkout moves.'
  printf '%s\n' "$PROJECT_ASSIGNMENT"
  echo '[ -f "$PI_SCIENCE_DIR/scripts/pi-science.sh" ] || { echo "Error: the Pi-Science checkout at $PI_SCIENCE_DIR is gone. Re-run scripts/install.sh from its new location." >&2; exit 1; }'
  echo 'exec bash "$PI_SCIENCE_DIR/scripts/pi-science.sh" "$@"'
} > "$LAUNCHER_TEMP"
chmod +x "$LAUNCHER_TEMP"

# Deterministic test barrier; normal installations never set this variable.
if [ -n "${PI_SCIENCE_TEST_LAUNCHER_COMMIT_BARRIER:-}" ]; then
  : > "${PI_SCIENCE_TEST_LAUNCHER_COMMIT_BARRIER}.ready"
  while [ ! -f "${PI_SCIENCE_TEST_LAUNCHER_COMMIT_BARRIER}.release" ]; do sleep 0.01; done
fi

if [ -e "$LAUNCHER" ] || [ -L "$LAUNCHER" ]; then
  launcher_is_owned || refuse_collision
  OLD_SNAPSHOT="$(mktemp "$BIN_DIR/.pi-science-launcher-old.XXXXXX")"
  rm -f "$OLD_SNAPSHOT"
  ln "$LAUNCHER" "$OLD_SNAPSHOT" || refuse_collision
  launcher_is_owned && [ "$LAUNCHER" -ef "$OLD_SNAPSHOT" ] || refuse_collision
  rm "$LAUNCHER" || refuse_collision
fi

if ! ln "$LAUNCHER_TEMP" "$LAUNCHER" 2>/dev/null; then
  if [ ! -e "$LAUNCHER" ] && [ ! -L "$LAUNCHER" ] && [ -n "$OLD_SNAPSHOT" ]; then ln "$OLD_SNAPSHOT" "$LAUNCHER" 2>/dev/null || true; fi
  refuse_collision
fi
rm -f "$LAUNCHER_TEMP" "$OLD_SNAPSHOT"
LAUNCHER_TEMP=""
OLD_SNAPSHOT=""
