import type { FastifyInstance } from "fastify";
import { configPath, readJson, writeJsonAtomic } from "../../storage/persistence.js";
import { endpointId } from "../../config/model-endpoint.js";

type Endpoint = { endpoint_id: string; name: string; base_url: string; protocol: string; enabled: boolean; health: string; model_schema: Record<string, unknown>; rate_limit: Record<string, unknown>; secret_ref?: string | null; data_egress: string; error?: string | null };

export interface ModelEndpointRouteDependencies { probeHealth?: (url: string) => Promise<{ ok: boolean }> }

/** Restores the /api/endpoints CRUD routes dropped with run-endpoint-routes.ts in 314b456; the settings UI still drives provider management through them. */
export function registerModelEndpointRoutes(app: FastifyInstance, deps: ModelEndpointRouteDependencies = {}): void {
  const probeHealth = deps.probeHealth ?? ((url: string) => fetch(url, { signal: AbortSignal.timeout(8_000) }));
  app.get("/api/endpoints", async () => ({ endpoints: await readJson<Endpoint[]>(configPath("model-endpoints.json"), []) }));
  app.post("/api/endpoints", async (request, reply) => { const body = (request.body ?? {}) as Record<string, unknown>; const name = String(body.name ?? "").trim(); const baseUrl = String(body.base_url ?? "").trim().replace(/\/$/, ""); if (!name || !/^https?:\/\//.test(baseUrl)) return reply.code(400).send({ error: "model endpoint name and absolute http(s) base_url are required" }); const endpoint: Endpoint = { endpoint_id: endpointId(name, baseUrl), name, base_url: baseUrl, protocol: String(body.protocol ?? "unknown"), enabled: true, health: "unknown", model_schema: typeof body.model_schema === "object" && body.model_schema ? body.model_schema as Record<string, unknown> : {}, rate_limit: typeof body.rate_limit === "object" && body.rate_limit ? body.rate_limit as Record<string, unknown> : {}, secret_ref: body.secret_ref ? String(body.secret_ref) : null, data_egress: String(body.data_egress ?? "remote"), error: null }; const rows = await readJson<Endpoint[]>(configPath("model-endpoints.json"), []); await writeJsonAtomic(configPath("model-endpoints.json"), [...rows.filter((row) => row.endpoint_id !== endpoint.endpoint_id), endpoint]); return endpoint; });
  app.put<{ Params: { endpoint_id: string } }>("/api/endpoints/:endpoint_id/enabled", async (request, reply) => { const rows = await readJson<Endpoint[]>(configPath("model-endpoints.json"), []); const item = rows.find((row) => row.endpoint_id === request.params.endpoint_id); if (!item) return reply.code(404).send({ error: "Model endpoint not found" }); const enabled = String((request.query as { enabled?: string }).enabled ?? "true") !== "false"; item.enabled = enabled; if (!enabled) item.health = "blocked"; await writeJsonAtomic(configPath("model-endpoints.json"), rows); return item; });
  app.post<{ Params: { endpoint_id: string } }>("/api/endpoints/:endpoint_id/health", async (request, reply) => { const rows = await readJson<Endpoint[]>(configPath("model-endpoints.json"), []); const item = rows.find((row) => row.endpoint_id === request.params.endpoint_id); if (!item) return reply.code(404).send({ error: "Model endpoint not found" }); if (!item.enabled) { item.health = "blocked"; item.error = "endpoint disabled"; } else { try { const response = await probeHealth(item.base_url); item.health = response.ok ? "ready" : "degraded"; item.error = null; } catch (error) { item.health = "error"; item.error = String(error instanceof Error ? error.message : error).slice(0, 300); } } await writeJsonAtomic(configPath("model-endpoints.json"), rows); return item; });
}
