import { randomUUID } from "node:crypto";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import type { FastifyInstance } from "fastify";
import { writeJsonAtomic } from "../../storage/persistence.js";
import { validateWorkspaceCwd } from "../../security/workspace-security.js";
import { ProjectReviewBusyError, type ProjectReviewService } from "../../project-review/service.js";
import { ensureKnowledgeItem, readProjectState as state, statePath, timestamp as now, type Source } from "../../project-review/project-state.js";
import type { ResearchLoopCoordinator } from "../../research-loop/coordinator.js";
import { subscribeResearchEvents } from "../../research-loop/events.js";
import { compileResearchIntent } from "../../research-loop/intent.js";

function q(request: { query: unknown }, key: string, fallback = "."): string { const value = (request.query as Record<string, unknown>)[key]; return typeof value === "string" && value ? value : fallback; }
async function ws(request: { query: unknown }, reply: { code: (status: number) => { send: (body: unknown) => unknown } }): Promise<string | null> { try { return await validateWorkspaceCwd(q(request, "cwd")); } catch (error) { reply.code(403).send({ error: String(error) }); return null; } }
async function projectContent(cwd: string): Promise<string> { const path = join(cwd, "PROJECT.md"); try { return await readFile(path, "utf8"); } catch { return `# ${(cwd.split(/[\\/]/).at(-1) ?? "Project").replaceAll("-", " ")}\n\n## Project Goal / 项目目标\n\nDescribe the project goal, scope, and constraints here.\n`; } }
function source(value: unknown): Source { const input = value && typeof value === "object" ? value as Record<string, unknown> : {}; return { session_id: typeof input.session_id === "string" ? input.session_id : null, message_ids: Array.isArray(input.message_ids) ? input.message_ids.map(String) : [], files: Array.isArray(input.files) ? input.files.map(String) : [], run_ids: Array.isArray(input.run_ids) ? input.run_ids.map(String) : [], citations: Array.isArray(input.citations) ? input.citations.map(String) : [] }; }

function researchFailure(reply: { code: (status: number) => { send: (body: unknown) => unknown } }, error: unknown) {
  const message = error instanceof Error ? error.message : String(error);
  const lower = message.toLowerCase();
  const status = lower.includes("not found") ? 404
    : lower.includes("already") || lower.includes("invalid loop transition") || lower.includes("cannot") || lower.includes("not running") ? 409
    : 400;
  return reply.code(status).send({ error: message });
}

export function registerProjectRoutes(app: FastifyInstance, research: ResearchLoopCoordinator, review: ProjectReviewService): void {
  // The ✨ Review button posts cwd in the body; the query form stays accepted so
  // the route matches the rest of this file.
  app.post("/api/project-knowledge/review", async (request, reply) => {
    const body = (request.body ?? {}) as { cwd?: unknown; session_id?: unknown; force_full_session?: unknown };
    let cwd: string;
    try { cwd = await validateWorkspaceCwd(typeof body.cwd === "string" && body.cwd ? body.cwd : q(request, "cwd")); }
    catch (error) { return reply.code(403).send({ error: String(error) }); }
    if (review.isRunning(cwd)) return reply.code(409).send({ error: "A project review is already running for this workspace" });
    try { return await review.run(cwd, { sessionId: typeof body.session_id === "string" ? body.session_id : null, forceFullSession: body.force_full_session === true, trigger: "manual" }); }
    catch (error) { return reply.code(error instanceof ProjectReviewBusyError ? 409 : 500).send({ error: error instanceof Error ? error.message : String(error) }); }
  });
  app.get("/api/project-knowledge/summary", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = await state(cwd); return { workspace: cwd, project_file: "PROJECT.md", pending_count: current.proposals.filter((item) => item.status === "pending").length, knowledge_count: current.items.filter((item) => item.status === "active").length, auto_review: current.policy.auto_review }; });
  app.post("/api/project-knowledge/initialize", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = await state(cwd); await writeJsonAtomic(statePath(cwd), current); return { workspace: cwd, project_file: "PROJECT.md", pending_count: 0, knowledge_count: current.items.length, auto_review: current.policy.auto_review }; });
  app.get("/api/project-knowledge/project", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = await state(cwd); return { workspace: cwd, project_file: "PROJECT.md", pending_count: current.proposals.filter((item) => item.status === "pending").length, knowledge_count: current.items.length, auto_review: current.policy.auto_review, content: await projectContent(cwd) }; });
  app.get("/api/project-knowledge/project/versions", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = await state(cwd); return { versions: current.project_versions.slice(-(Number((request.query as { limit?: string }).limit ?? 100))).reverse().map(({ content: _content, ...item }) => item) }; });
  app.post<{ Params: { version_id: string } }>("/api/project-knowledge/project/versions/:version_id/restore", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = await state(cwd); const version = current.project_versions.find((item) => item.id === request.params.version_id); if (!version) return reply.code(404).send({ error: "Project document version not found" }); await mkdir(cwd, { recursive: true }); await writeFile(join(cwd, "PROJECT.md"), version.content, "utf8"); return { ok: true, content: version.content, version_id: version.id }; });
  app.get("/api/project-knowledge/items", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = await state(cwd); const include = String((request.query as { include_inactive?: string }).include_inactive ?? "true") !== "false"; return { items: include ? current.items : current.items.filter((item) => item.status === "active") }; });
  app.get("/api/project-knowledge/proposals", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = await state(cwd); const status = (request.query as { status?: string }).status; const proposals = status ? current.proposals.filter((item) => item.status === status) : current.proposals; return { proposals, pending_count: current.proposals.filter((item) => item.status === "pending").length }; });
  app.get("/api/project-knowledge/proposals/count", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; return { pending_count: (await state(cwd)).proposals.filter((item) => item.status === "pending").length }; });
  app.patch<{ Params: { proposal_id: string } }>("/api/project-knowledge/proposals/:proposal_id", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = await state(cwd); const item = current.proposals.find((row) => row.id === request.params.proposal_id); if (!item) return reply.code(404).send({ error: "Proposal not found" }); if (item.status !== "pending") return reply.code(409).send({ error: "Only pending proposals can be edited" }); Object.assign(item, request.body as Record<string, unknown>, { updated_at: now() }); await writeJsonAtomic(statePath(cwd), current); return { proposal: item }; });
  app.get<{ Params: { proposal_id: string } }>("/api/project-knowledge/proposals/:proposal_id/preview", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const item = (await state(cwd)).proposals.find((row) => row.id === request.params.proposal_id); if (!item) return reply.code(404).send({ error: "Proposal not found" }); return { ok: true, proposal_type: item.proposal_type, before: "", after: `${item.title}\n${item.summary}`, conflicts_with: item.conflicts_with, supersedes: item.supersedes }; });
  app.post<{ Params: { proposal_id: string } }>("/api/project-knowledge/proposals/:proposal_id/accept", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = await state(cwd); const proposal = current.proposals.find((row) => row.id === request.params.proposal_id); if (!proposal) return reply.code(404).send({ error: "Proposal not found" }); if (proposal.status !== "pending") return reply.code(409).send({ error: "Proposal is not pending" }); const body = (request.body ?? {}) as { title?: string; summary?: string }; proposal.status = "accepted"; proposal.updated_at = now(); proposal.decision_reason = null; if (body.title) proposal.title = body.title; if (body.summary) proposal.summary = body.summary; const knowledgeItem = ensureKnowledgeItem(current, proposal); if (knowledgeItem) { await writeJsonAtomic(statePath(cwd), current); return { ok: true, proposal_id: proposal.id, knowledge_item: knowledgeItem }; } await writeJsonAtomic(statePath(cwd), current); return { ok: true, proposal_id: proposal.id, file_operation: { id: `history-${randomUUID().slice(0, 12)}`, operations: proposal.operations } }; });
  app.post<{ Params: { proposal_id: string } }>("/api/project-knowledge/proposals/:proposal_id/reject", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = await state(cwd); const proposal = current.proposals.find((row) => row.id === request.params.proposal_id); if (!proposal) return reply.code(404).send({ error: "Proposal not found" }); if (proposal.status !== "pending") return reply.code(409).send({ error: "Proposal is not pending" }); proposal.status = "rejected"; proposal.decision_reason = String(((request.body ?? {}) as { reason?: unknown }).reason ?? ""); proposal.updated_at = now(); await writeJsonAtomic(statePath(cwd), current); return { ok: true, proposal }; });
  app.post("/api/project-knowledge/proposals/batch", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const body = (request.body ?? {}) as { proposal_ids?: unknown; action?: string; reason?: string }; if (body.action !== "accept" && body.action !== "reject") return reply.code(400).send({ error: "Batch action must be accept or reject" }); const current = await state(cwd); const failures: unknown[] = []; const results: unknown[] = []; for (const id of Array.isArray(body.proposal_ids) ? body.proposal_ids.map(String) : []) { const proposal = current.proposals.find((row) => row.id === id); if (!proposal || proposal.status !== "pending") failures.push({ proposal_id: id, status: 409, detail: "Proposal is not pending" }); else { proposal.status = body.action === "accept" ? "accepted" : "rejected"; proposal.decision_reason = body.reason ?? null; proposal.updated_at = now(); const knowledgeItem = body.action === "accept" ? ensureKnowledgeItem(current, proposal) : null; results.push({ proposal_id: id, status: proposal.status, ...(knowledgeItem ? { knowledge_item: knowledgeItem } : {}) }); } } await writeJsonAtomic(statePath(cwd), current); return { ok: failures.length === 0, results, failures }; });
  app.get("/api/project-knowledge/policy", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; return (await state(cwd)).policy; });
  app.patch("/api/project-knowledge/policy", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = await state(cwd); Object.assign(current.policy, request.body as Record<string, unknown>, { updated_at: now() }); await writeJsonAtomic(statePath(cwd), current); return current.policy; });
  app.get("/api/project-knowledge/history", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; return { history: (await state(cwd)).history }; });
  app.get("/api/project-knowledge/files/views", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; return { updated_at: now(), files: [], by_type: {}, by_topic: {}, by_month: {} }; });
  app.post<{ Params: { history_id: string } }>("/api/project-knowledge/file-operations/:history_id/undo", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const current = await state(cwd); return current.history.some((item) => item.id === request.params.history_id) ? { ok: true, undo: { id: request.params.history_id, status: "not_required" } } : reply.code(404).send({ error: "File operation history not found" }); });

  app.get("/api/project-memory/overview", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; await research.reconcile(cwd); const current = await state(cwd); const repository = research.repository(cwd); const rows = await repository.records(); const researchLoops = await repository.loops(); const details = await Promise.all(researchLoops.map((loop) => research.detail(cwd, loop.loop_id))); const candidates = details.flatMap((detail) => detail?.candidates ?? []); return { workspace: cwd, project_file: "PROJECT.md", pending_count: current.proposals.filter((item) => item.status === "pending").length, knowledge_count: current.items.length, auto_review: current.policy.auto_review, run_count: candidates.filter((item) => Object.keys(item.execution).length).length, artifact_count: candidates.reduce((sum, item) => sum + (item.evaluation?.artifact_refs.length ?? 0), 0), result_review_count: candidates.filter((item) => item.evaluation).length, research_record_count: rows.length, research_loop_count: researchLoops.length, active_research_loop_count: researchLoops.filter((item) => ["ready", "running", "pausing", "paused", "cancelling", "needs_attention"].includes(item.status)).length }; });
  app.get("/api/project-memory/timeline", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; return { timeline: (await research.repository(cwd).records()).reverse().slice(0, Number((request.query as { limit?: string }).limit ?? 200)) }; });
  app.post("/api/project-memory/index/rebuild", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const count = (await research.repository(cwd).records()).length; return { ok: true, indexed_at: now(), records: count }; });
  app.get("/api/project-memory/research-events", async (request, reply) => {
    const cwd = await ws(request, reply); if (!cwd) return;
    // Lossy invalidation channel: clients refetch full state on every signal, so
    // no replay or backpressure buffering is needed (compare sse-routes.ts).
    reply.hijack();
    reply.raw.writeHead(200, { "content-type": "text/event-stream", "cache-control": "no-cache", connection: "keep-alive" });
    const push = (text: string) => { if (!reply.raw.destroyed && !reply.raw.writableEnded) reply.raw.write(text); };
    push(": connected\n\n");
    const unsubscribe = subscribeResearchEvents(cwd, (event) => push(`data: ${JSON.stringify(event)}\n\n`));
    const heartbeat = setInterval(() => push(": ping\n\n"), 15_000);
    let closed = false;
    const cleanup = () => { if (closed) return; closed = true; clearInterval(heartbeat); unsubscribe(); };
    request.raw.once("close", cleanup);
    reply.raw.once("close", cleanup);
  });
  app.post("/api/project-memory/research-loop-intents", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; try { return compileResearchIntent(request.body); } catch (error) { return researchFailure(reply, error); } });
  app.get("/api/project-memory/research-loops", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; await research.reconcile(cwd); return { loops: await research.list(cwd) }; });
  app.post("/api/project-memory/research-loops", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; try { return await research.create(cwd, request.body); } catch (error) { return researchFailure(reply, error); } });
  app.get<{ Params: { loop_id: string } }>("/api/project-memory/research-loops/:loop_id", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; research.resume(cwd, request.params.loop_id); return await research.detail(cwd, request.params.loop_id) ?? reply.code(404).send({ error: "Research loop not found" }); });
  app.post<{ Params: { loop_id: string } }>("/api/project-memory/research-loops/:loop_id/preflight", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; try { return await research.preflight(cwd, request.params.loop_id); } catch (error) { return researchFailure(reply, error); } });
  app.post<{ Params: { loop_id: string; action: string } }>("/api/project-memory/research-loops/:loop_id/:action", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; try { return await research.action(cwd, request.params.loop_id, request.params.action); } catch (error) { return researchFailure(reply, error); } });
  app.get("/api/project-memory/experiences", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const loopId = String((request.query as { loop_id?: string }).loop_id ?? ""); if (loopId) return { experiences: (await research.detail(cwd, loopId))?.candidates ?? [] }; const loops = await research.list(cwd); const details = await Promise.all(loops.map((loop) => research.detail(cwd, loop.loop_id))); return { experiences: details.flatMap((detail) => detail?.candidates ?? []) }; });
  app.get<{ Params: { loop_id: string } }>("/api/project-memory/research-loops/:loop_id/frontier", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const detail = await research.detail(cwd, request.params.loop_id); return detail ? { frontier: detail.frontier } : reply.code(404).send({ error: "Research loop not found" }); });
  app.get("/api/project-memory/evaluators", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; return { evaluators: await research.evaluators(cwd) }; });
  app.post("/api/project-memory/evaluators", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; try { return await research.registerEvaluator(cwd, request.body); } catch (error) { return researchFailure(reply, error); } });
  app.get<{ Params: { evaluator_id: string; version: string } }>("/api/project-memory/evaluators/:evaluator_id/versions/:version", async (request, reply) => { const cwd = await ws(request, reply); if (!cwd) return; const evaluator = (await research.evaluators(cwd)).find((item) => item.evaluator_id === request.params.evaluator_id && item.version === Number(request.params.version)); return evaluator ?? reply.code(404).send({ error: "Evaluator version not found" }); });
}
